// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.21.12
// source: protobuf_pydantic_gen/pydantic.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "pydantic";

/** Field options for pydantic */
export interface FieldOptions {
  description?: string | undefined;
  default?: string | undefined;
  required?: boolean | undefined;
}

/** Method auth options */
export interface MethodAuth {
  required?: boolean | undefined;
  scopes: string[];
}

/** Method extra options */
export interface MethodExtra {
  is_redirect?: boolean | undefined;
}

function createBaseFieldOptions(): FieldOptions {
  return { description: undefined, default: undefined, required: undefined };
}

export const FieldOptions: MessageFns<FieldOptions> = {
  encode(message: FieldOptions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.description !== undefined) {
      writer.uint32(10).string(message.description);
    }
    if (message.default !== undefined) {
      writer.uint32(18).string(message.default);
    }
    if (message.required !== undefined) {
      writer.uint32(24).bool(message.required);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FieldOptions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFieldOptions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.default = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.required = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FieldOptions {
    return {
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      default: isSet(object.default) ? globalThis.String(object.default) : undefined,
      required: isSet(object.required) ? globalThis.Boolean(object.required) : undefined,
    };
  },

  toJSON(message: FieldOptions): unknown {
    const obj: any = {};
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.default !== undefined) {
      obj.default = message.default;
    }
    if (message.required !== undefined) {
      obj.required = message.required;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FieldOptions>, I>>(base?: I): FieldOptions {
    return FieldOptions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FieldOptions>, I>>(object: I): FieldOptions {
    const message = createBaseFieldOptions();
    message.description = object.description ?? undefined;
    message.default = object.default ?? undefined;
    message.required = object.required ?? undefined;
    return message;
  },
};

function createBaseMethodAuth(): MethodAuth {
  return { required: undefined, scopes: [] };
}

export const MethodAuth: MessageFns<MethodAuth> = {
  encode(message: MethodAuth, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.required !== undefined) {
      writer.uint32(8).bool(message.required);
    }
    for (const v of message.scopes) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MethodAuth {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMethodAuth();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.required = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.scopes.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MethodAuth {
    return {
      required: isSet(object.required) ? globalThis.Boolean(object.required) : undefined,
      scopes: globalThis.Array.isArray(object?.scopes) ? object.scopes.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: MethodAuth): unknown {
    const obj: any = {};
    if (message.required !== undefined) {
      obj.required = message.required;
    }
    if (message.scopes?.length) {
      obj.scopes = message.scopes;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MethodAuth>, I>>(base?: I): MethodAuth {
    return MethodAuth.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MethodAuth>, I>>(object: I): MethodAuth {
    const message = createBaseMethodAuth();
    message.required = object.required ?? undefined;
    message.scopes = object.scopes?.map((e) => e) || [];
    return message;
  },
};

function createBaseMethodExtra(): MethodExtra {
  return { is_redirect: undefined };
}

export const MethodExtra: MessageFns<MethodExtra> = {
  encode(message: MethodExtra, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.is_redirect !== undefined) {
      writer.uint32(8).bool(message.is_redirect);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MethodExtra {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMethodExtra();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.is_redirect = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MethodExtra {
    return {
      is_redirect: isSet(object.isRedirect)
        ? globalThis.Boolean(object.isRedirect)
        : isSet(object.is_redirect)
        ? globalThis.Boolean(object.is_redirect)
        : undefined,
    };
  },

  toJSON(message: MethodExtra): unknown {
    const obj: any = {};
    if (message.is_redirect !== undefined) {
      obj.isRedirect = message.is_redirect;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MethodExtra>, I>>(base?: I): MethodExtra {
    return MethodExtra.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MethodExtra>, I>>(object: I): MethodExtra {
    const message = createBaseMethodExtra();
    message.is_redirect = object.is_redirect ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
