// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.21.12
// source: stew/api/v1/options.proto

/* eslint-disable */

export const protobufPackage = "stew.api.v1";
