// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.21.12
// source: stew/api/v1/resource.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../../../google/protobuf/timestamp";

export const protobufPackage = "stew.api.v1";

/** 权限资源表 (Resources) */
export interface Resource {
  /** @gotags: gorm:"primaryKey;autoIncrement;comment:自增id" */
  ID: number;
  /** @gotags: json:"resource_key" gorm:"column:resource_key;type:varchar(36);comment:资源id" */
  ResourceKey: string;
  /** @gotags: json:"resource_name" gorm:"column:resource_name;type:varchar(128);comment:资源名称" */
  ResourceName: string;
  /** @gotags: json:"resource_table" gorm:"column:resource_table;type:varchar(128);comment:资源表名称" */
  ResourceTable: string;
  /** @gotags: doc:"任务ID" json:"uid" gorm:"column:uid;type:varchar(36);comment:uid" */
  uid: string;
  /** @gotags: doc:"完成时间" gorm:"column:completed_at;type:datetime;serializer:timepb;comment:定时任务的最近一次完成时间" */
  created_at:
    | Date
    | undefined;
  /** @gotags: doc:"更新时间" gorm:"autoUpdateTime;column:updated_at;type:datetime;serializer:timepb;comment:定时任务的更新时间" */
  updated_at: Date | undefined;
}

function createBaseResource(): Resource {
  return {
    ID: 0,
    ResourceKey: "",
    ResourceName: "",
    ResourceTable: "",
    uid: "",
    created_at: undefined,
    updated_at: undefined,
  };
}

export const Resource: MessageFns<Resource> = {
  encode(message: Resource, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ID !== 0) {
      writer.uint32(8).int64(message.ID);
    }
    if (message.ResourceKey !== "") {
      writer.uint32(18).string(message.ResourceKey);
    }
    if (message.ResourceName !== "") {
      writer.uint32(26).string(message.ResourceName);
    }
    if (message.ResourceTable !== "") {
      writer.uint32(34).string(message.ResourceTable);
    }
    if (message.uid !== "") {
      writer.uint32(42).string(message.uid);
    }
    if (message.created_at !== undefined) {
      Timestamp.encode(toTimestamp(message.created_at), writer.uint32(50).fork()).join();
    }
    if (message.updated_at !== undefined) {
      Timestamp.encode(toTimestamp(message.updated_at), writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Resource {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResource();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ID = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ResourceKey = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ResourceName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ResourceTable = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.uid = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.created_at = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.updated_at = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Resource {
    return {
      ID: isSet(object.ID) ? globalThis.Number(object.ID) : 0,
      ResourceKey: isSet(object.ResourceKey) ? globalThis.String(object.ResourceKey) : "",
      ResourceName: isSet(object.ResourceName) ? globalThis.String(object.ResourceName) : "",
      ResourceTable: isSet(object.ResourceTable) ? globalThis.String(object.ResourceTable) : "",
      uid: isSet(object.uid) ? globalThis.String(object.uid) : "",
      created_at: isSet(object.createdAt)
        ? fromJsonTimestamp(object.createdAt)
        : isSet(object.created_at)
        ? fromJsonTimestamp(object.created_at)
        : undefined,
      updated_at: isSet(object.updatedAt)
        ? fromJsonTimestamp(object.updatedAt)
        : isSet(object.updated_at)
        ? fromJsonTimestamp(object.updated_at)
        : undefined,
    };
  },

  toJSON(message: Resource): unknown {
    const obj: any = {};
    if (message.ID !== 0) {
      obj.ID = Math.round(message.ID);
    }
    if (message.ResourceKey !== "") {
      obj.ResourceKey = message.ResourceKey;
    }
    if (message.ResourceName !== "") {
      obj.ResourceName = message.ResourceName;
    }
    if (message.ResourceTable !== "") {
      obj.ResourceTable = message.ResourceTable;
    }
    if (message.uid !== "") {
      obj.uid = message.uid;
    }
    if (message.created_at !== undefined) {
      obj.createdAt = message.created_at.toISOString();
    }
    if (message.updated_at !== undefined) {
      obj.updatedAt = message.updated_at.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Resource>, I>>(base?: I): Resource {
    return Resource.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Resource>, I>>(object: I): Resource {
    const message = createBaseResource();
    message.ID = object.ID ?? 0;
    message.ResourceKey = object.ResourceKey ?? "";
    message.ResourceName = object.ResourceName ?? "";
    message.ResourceTable = object.ResourceTable ?? "";
    message.uid = object.uid ?? "";
    message.created_at = object.created_at ?? undefined;
    message.updated_at = object.updated_at ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
