// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.21.12
// source: stew/api/v1/web.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Struct } from "../../../google/protobuf/struct";

export const protobufPackage = "stew.api.v1";

export enum Code {
  UNKNOWN = 0,
  OK = 2000,
  /** PARAMS_ERROR - 请求参数错误 */
  PARAMS_ERROR = 4000,
  /** AUTH_ERROR - AUTH_ERROR */
  AUTH_ERROR = 4001,
  PREMISSION_DENIED = 4003,
  NOT_FOUND = 4004,
  TOKEN_NOT_FOUND = 4006,
  RESOURCE_EXHAUSTED = 4008,
  INTERNAL_ERROR = 5000,
  NOT_IMPLEMENTED = 5001,
  TIMEOUT_ERROR = 5004,
  METADATA_MISSING = 4007,
  CONFLICT = 4009,
  UNRECOGNIZED = -1,
}

export function codeFromJSON(object: any): Code {
  switch (object) {
    case 0:
    case "UNKNOWN":
      return Code.UNKNOWN;
    case 2000:
    case "OK":
      return Code.OK;
    case 4000:
    case "PARAMS_ERROR":
      return Code.PARAMS_ERROR;
    case 4001:
    case "AUTH_ERROR":
      return Code.AUTH_ERROR;
    case 4003:
    case "PREMISSION_DENIED":
      return Code.PREMISSION_DENIED;
    case 4004:
    case "NOT_FOUND":
      return Code.NOT_FOUND;
    case 4006:
    case "TOKEN_NOT_FOUND":
      return Code.TOKEN_NOT_FOUND;
    case 4008:
    case "RESOURCE_EXHAUSTED":
      return Code.RESOURCE_EXHAUSTED;
    case 5000:
    case "INTERNAL_ERROR":
      return Code.INTERNAL_ERROR;
    case 5001:
    case "NOT_IMPLEMENTED":
      return Code.NOT_IMPLEMENTED;
    case 5004:
    case "TIMEOUT_ERROR":
      return Code.TIMEOUT_ERROR;
    case 4007:
    case "METADATA_MISSING":
      return Code.METADATA_MISSING;
    case 4009:
    case "CONFLICT":
      return Code.CONFLICT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Code.UNRECOGNIZED;
  }
}

export function codeToJSON(object: Code): string {
  switch (object) {
    case Code.UNKNOWN:
      return "UNKNOWN";
    case Code.OK:
      return "OK";
    case Code.PARAMS_ERROR:
      return "PARAMS_ERROR";
    case Code.AUTH_ERROR:
      return "AUTH_ERROR";
    case Code.PREMISSION_DENIED:
      return "PREMISSION_DENIED";
    case Code.NOT_FOUND:
      return "NOT_FOUND";
    case Code.TOKEN_NOT_FOUND:
      return "TOKEN_NOT_FOUND";
    case Code.RESOURCE_EXHAUSTED:
      return "RESOURCE_EXHAUSTED";
    case Code.INTERNAL_ERROR:
      return "INTERNAL_ERROR";
    case Code.NOT_IMPLEMENTED:
      return "NOT_IMPLEMENTED";
    case Code.TIMEOUT_ERROR:
      return "TIMEOUT_ERROR";
    case Code.METADATA_MISSING:
      return "METADATA_MISSING";
    case Code.CONFLICT:
      return "CONFLICT";
    case Code.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface APIResponse {
  message: string;
  code: number;
  response_type: string;
  data: Uint8Array;
}

export interface HttpResponse {
  message: string;
  code: number;
  data: { [key: string]: any } | undefined;
}

export interface EventStreamResponse {
  event: string;
  data: string;
  id: number;
  retry: number;
}

export interface RedirectResponse {
  url: string;
  code: number;
}

/** } */
export interface Errors {
  code: number;
  message: string;
  action: string;
  file: string;
  line: number;
  fn: string;
  stack: string;
  to_client_message: string;
}

export interface Headers {
  Uid: string;
  authentication: string;
  filename: string;
  token: string;
}

export interface EventStream {
  event: string;
  data: string;
  id: number;
  retry: number;
}

function createBaseAPIResponse(): APIResponse {
  return { message: "", code: 0, response_type: "", data: new Uint8Array(0) };
}

export const APIResponse: MessageFns<APIResponse> = {
  encode(message: APIResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.code !== 0) {
      writer.uint32(17).double(message.code);
    }
    if (message.response_type !== "") {
      writer.uint32(26).string(message.response_type);
    }
    if (message.data.length !== 0) {
      writer.uint32(34).bytes(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): APIResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAPIResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.code = reader.double();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.response_type = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): APIResponse {
    return {
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      response_type: isSet(object.response_type) ? globalThis.String(object.response_type) : "",
      data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0),
    };
  },

  toJSON(message: APIResponse): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.code !== 0) {
      obj.code = message.code;
    }
    if (message.response_type !== "") {
      obj.response_type = message.response_type;
    }
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<APIResponse>, I>>(base?: I): APIResponse {
    return APIResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<APIResponse>, I>>(object: I): APIResponse {
    const message = createBaseAPIResponse();
    message.message = object.message ?? "";
    message.code = object.code ?? 0;
    message.response_type = object.response_type ?? "";
    message.data = object.data ?? new Uint8Array(0);
    return message;
  },
};

function createBaseHttpResponse(): HttpResponse {
  return { message: "", code: 0, data: undefined };
}

export const HttpResponse: MessageFns<HttpResponse> = {
  encode(message: HttpResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    if (message.data !== undefined) {
      Struct.encode(Struct.wrap(message.data), writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HttpResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHttpResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.data = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HttpResponse {
    return {
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      data: isObject(object.data) ? object.data : undefined,
    };
  },

  toJSON(message: HttpResponse): unknown {
    const obj: any = {};
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.data !== undefined) {
      obj.data = message.data;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HttpResponse>, I>>(base?: I): HttpResponse {
    return HttpResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HttpResponse>, I>>(object: I): HttpResponse {
    const message = createBaseHttpResponse();
    message.message = object.message ?? "";
    message.code = object.code ?? 0;
    message.data = object.data ?? undefined;
    return message;
  },
};

function createBaseEventStreamResponse(): EventStreamResponse {
  return { event: "", data: "", id: 0, retry: 0 };
}

export const EventStreamResponse: MessageFns<EventStreamResponse> = {
  encode(message: EventStreamResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.event !== "") {
      writer.uint32(10).string(message.event);
    }
    if (message.data !== "") {
      writer.uint32(18).string(message.data);
    }
    if (message.id !== 0) {
      writer.uint32(24).int64(message.id);
    }
    if (message.retry !== 0) {
      writer.uint32(32).int32(message.retry);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventStreamResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventStreamResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.event = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.retry = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventStreamResponse {
    return {
      event: isSet(object.event) ? globalThis.String(object.event) : "",
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      retry: isSet(object.retry) ? globalThis.Number(object.retry) : 0,
    };
  },

  toJSON(message: EventStreamResponse): unknown {
    const obj: any = {};
    if (message.event !== "") {
      obj.event = message.event;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.retry !== 0) {
      obj.retry = Math.round(message.retry);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventStreamResponse>, I>>(base?: I): EventStreamResponse {
    return EventStreamResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventStreamResponse>, I>>(object: I): EventStreamResponse {
    const message = createBaseEventStreamResponse();
    message.event = object.event ?? "";
    message.data = object.data ?? "";
    message.id = object.id ?? 0;
    message.retry = object.retry ?? 0;
    return message;
  },
};

function createBaseRedirectResponse(): RedirectResponse {
  return { url: "", code: 0 };
}

export const RedirectResponse: MessageFns<RedirectResponse> = {
  encode(message: RedirectResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.url !== "") {
      writer.uint32(10).string(message.url);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RedirectResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRedirectResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RedirectResponse {
    return {
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
    };
  },

  toJSON(message: RedirectResponse): unknown {
    const obj: any = {};
    if (message.url !== "") {
      obj.url = message.url;
    }
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RedirectResponse>, I>>(base?: I): RedirectResponse {
    return RedirectResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RedirectResponse>, I>>(object: I): RedirectResponse {
    const message = createBaseRedirectResponse();
    message.url = object.url ?? "";
    message.code = object.code ?? 0;
    return message;
  },
};

function createBaseErrors(): Errors {
  return { code: 0, message: "", action: "", file: "", line: 0, fn: "", stack: "", to_client_message: "" };
}

export const Errors: MessageFns<Errors> = {
  encode(message: Errors, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== 0) {
      writer.uint32(8).int32(message.code);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.action !== "") {
      writer.uint32(26).string(message.action);
    }
    if (message.file !== "") {
      writer.uint32(34).string(message.file);
    }
    if (message.line !== 0) {
      writer.uint32(40).int32(message.line);
    }
    if (message.fn !== "") {
      writer.uint32(50).string(message.fn);
    }
    if (message.stack !== "") {
      writer.uint32(58).string(message.stack);
    }
    if (message.to_client_message !== "") {
      writer.uint32(66).string(message.to_client_message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Errors {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrors();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.action = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.file = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.line = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.fn = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.stack = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.to_client_message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Errors {
    return {
      code: isSet(object.code) ? globalThis.Number(object.code) : 0,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      action: isSet(object.action) ? globalThis.String(object.action) : "",
      file: isSet(object.file) ? globalThis.String(object.file) : "",
      line: isSet(object.line) ? globalThis.Number(object.line) : 0,
      fn: isSet(object.fn) ? globalThis.String(object.fn) : "",
      stack: isSet(object.stack) ? globalThis.String(object.stack) : "",
      to_client_message: isSet(object.toClientMessage)
        ? globalThis.String(object.toClientMessage)
        : isSet(object.to_client_message)
        ? globalThis.String(object.to_client_message)
        : "",
    };
  },

  toJSON(message: Errors): unknown {
    const obj: any = {};
    if (message.code !== 0) {
      obj.code = Math.round(message.code);
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.action !== "") {
      obj.action = message.action;
    }
    if (message.file !== "") {
      obj.file = message.file;
    }
    if (message.line !== 0) {
      obj.line = Math.round(message.line);
    }
    if (message.fn !== "") {
      obj.fn = message.fn;
    }
    if (message.stack !== "") {
      obj.stack = message.stack;
    }
    if (message.to_client_message !== "") {
      obj.toClientMessage = message.to_client_message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Errors>, I>>(base?: I): Errors {
    return Errors.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Errors>, I>>(object: I): Errors {
    const message = createBaseErrors();
    message.code = object.code ?? 0;
    message.message = object.message ?? "";
    message.action = object.action ?? "";
    message.file = object.file ?? "";
    message.line = object.line ?? 0;
    message.fn = object.fn ?? "";
    message.stack = object.stack ?? "";
    message.to_client_message = object.to_client_message ?? "";
    return message;
  },
};

function createBaseHeaders(): Headers {
  return { Uid: "", authentication: "", filename: "", token: "" };
}

export const Headers: MessageFns<Headers> = {
  encode(message: Headers, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.Uid !== "") {
      writer.uint32(10).string(message.Uid);
    }
    if (message.authentication !== "") {
      writer.uint32(18).string(message.authentication);
    }
    if (message.filename !== "") {
      writer.uint32(26).string(message.filename);
    }
    if (message.token !== "") {
      writer.uint32(34).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Headers {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeaders();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.Uid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.authentication = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Headers {
    return {
      Uid: isSet(object.Uid) ? globalThis.String(object.Uid) : "",
      authentication: isSet(object.authentication) ? globalThis.String(object.authentication) : "",
      filename: isSet(object.filename) ? globalThis.String(object.filename) : "",
      token: isSet(object.token) ? globalThis.String(object.token) : "",
    };
  },

  toJSON(message: Headers): unknown {
    const obj: any = {};
    if (message.Uid !== "") {
      obj.Uid = message.Uid;
    }
    if (message.authentication !== "") {
      obj.authentication = message.authentication;
    }
    if (message.filename !== "") {
      obj.filename = message.filename;
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Headers>, I>>(base?: I): Headers {
    return Headers.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Headers>, I>>(object: I): Headers {
    const message = createBaseHeaders();
    message.Uid = object.Uid ?? "";
    message.authentication = object.authentication ?? "";
    message.filename = object.filename ?? "";
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseEventStream(): EventStream {
  return { event: "", data: "", id: 0, retry: 0 };
}

export const EventStream: MessageFns<EventStream> = {
  encode(message: EventStream, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.event !== "") {
      writer.uint32(10).string(message.event);
    }
    if (message.data !== "") {
      writer.uint32(18).string(message.data);
    }
    if (message.id !== 0) {
      writer.uint32(24).int64(message.id);
    }
    if (message.retry !== 0) {
      writer.uint32(32).int32(message.retry);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventStream {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventStream();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.event = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.data = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.retry = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventStream {
    return {
      event: isSet(object.event) ? globalThis.String(object.event) : "",
      data: isSet(object.data) ? globalThis.String(object.data) : "",
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      retry: isSet(object.retry) ? globalThis.Number(object.retry) : 0,
    };
  },

  toJSON(message: EventStream): unknown {
    const obj: any = {};
    if (message.event !== "") {
      obj.event = message.event;
    }
    if (message.data !== "") {
      obj.data = message.data;
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.retry !== 0) {
      obj.retry = Math.round(message.retry);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventStream>, I>>(base?: I): EventStream {
    return EventStream.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventStream>, I>>(object: I): EventStream {
    const message = createBaseEventStream();
    message.event = object.event ?? "";
    message.data = object.data ?? "";
    message.id = object.id ?? 0;
    message.retry = object.retry ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
