// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.21.12
// source: apikey.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Empty } from "./google/protobuf/empty";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "stew.api.v1";

/** API Key 信息 */
export interface ApiKey {
  id: string;
  name: string;
  key: string;
  user_id: string;
  description: string;
  scopes: string[];
  created_at: Date | undefined;
  expires_at: Date | undefined;
  last_used_at: Date | undefined;
  is_active: boolean;
  metadata: { [key: string]: string };
}

export interface ApiKey_MetadataEntry {
  key: string;
  value: string;
}

/** 创建 API Key 请求 */
export interface CreateApiKeyRequest {
  name: string;
  user_id: string;
  scopes: string[];
  expires_at: Date | undefined;
  metadata: { [key: string]: string };
  description: string;
}

export interface CreateApiKeyRequest_MetadataEntry {
  key: string;
  value: string;
}

/** 创建 API Key 响应 */
export interface CreateApiKeyResponse {
  api_key: ApiKey | undefined;
  raw_key: string;
}

/** 列出 API Keys 请求 */
export interface ListApiKeysRequest {
  user_id: string;
  page: number;
  limit: number;
  include_inactive: boolean;
}

/** 列出 API Keys 响应 */
export interface ListApiKeysResponse {
  api_keys: ApiKey[];
  total: number;
  page: number;
  limit: number;
}

/** 获取 API Key 请求 */
export interface GetApiKeyRequest {
  id: string;
}

/** 更新 API Key 请求 */
export interface UpdateApiKeyRequest {
  id: string;
  name: string;
  scopes: string[];
  expires_at: Date | undefined;
  is_active: boolean;
  metadata: { [key: string]: string };
}

export interface UpdateApiKeyRequest_MetadataEntry {
  key: string;
  value: string;
}

/** 删除 API Key 请求 */
export interface DeleteApiKeyRequest {
  id: string;
}

/** 验证 API Key 请求 */
export interface ValidateApiKeyRequest {
  api_key: string;
  required_scopes: string[];
}

/** 验证 API Key 响应 */
export interface ValidateApiKeyResponse {
  is_valid: boolean;
  api_key: ApiKey | undefined;
  error_message: string;
}

/** 轮换 API Key 请求 */
export interface RotateApiKeyRequest {
  id: string;
}

/** 轮换 API Key 响应 */
export interface RotateApiKeyResponse {
  api_key: ApiKey | undefined;
  raw_key: string;
}

function createBaseApiKey(): ApiKey {
  return {
    id: "",
    name: "",
    key: "",
    user_id: "",
    description: "",
    scopes: [],
    created_at: undefined,
    expires_at: undefined,
    last_used_at: undefined,
    is_active: false,
    metadata: {},
  };
}

export const ApiKey: MessageFns<ApiKey> = {
  encode(message: ApiKey, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.key !== "") {
      writer.uint32(26).string(message.key);
    }
    if (message.user_id !== "") {
      writer.uint32(34).string(message.user_id);
    }
    if (message.description !== "") {
      writer.uint32(90).string(message.description);
    }
    for (const v of message.scopes) {
      writer.uint32(42).string(v!);
    }
    if (message.created_at !== undefined) {
      Timestamp.encode(toTimestamp(message.created_at), writer.uint32(50).fork()).join();
    }
    if (message.expires_at !== undefined) {
      Timestamp.encode(toTimestamp(message.expires_at), writer.uint32(58).fork()).join();
    }
    if (message.last_used_at !== undefined) {
      Timestamp.encode(toTimestamp(message.last_used_at), writer.uint32(66).fork()).join();
    }
    if (message.is_active !== false) {
      writer.uint32(72).bool(message.is_active);
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      ApiKey_MetadataEntry.encode({ key: key as any, value }, writer.uint32(82).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApiKey {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApiKey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.scopes.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.created_at = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.expires_at = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.last_used_at = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.is_active = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          const entry10 = ApiKey_MetadataEntry.decode(reader, reader.uint32());
          if (entry10.value !== undefined) {
            message.metadata[entry10.key] = entry10.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApiKey {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      scopes: globalThis.Array.isArray(object?.scopes) ? object.scopes.map((e: any) => globalThis.String(e)) : [],
      created_at: isSet(object.created_at) ? fromJsonTimestamp(object.created_at) : undefined,
      expires_at: isSet(object.expires_at) ? fromJsonTimestamp(object.expires_at) : undefined,
      last_used_at: isSet(object.last_used_at) ? fromJsonTimestamp(object.last_used_at) : undefined,
      is_active: isSet(object.is_active) ? globalThis.Boolean(object.is_active) : false,
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: ApiKey): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.scopes?.length) {
      obj.scopes = message.scopes;
    }
    if (message.created_at !== undefined) {
      obj.created_at = message.created_at.toISOString();
    }
    if (message.expires_at !== undefined) {
      obj.expires_at = message.expires_at.toISOString();
    }
    if (message.last_used_at !== undefined) {
      obj.last_used_at = message.last_used_at.toISOString();
    }
    if (message.is_active !== false) {
      obj.is_active = message.is_active;
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApiKey>, I>>(base?: I): ApiKey {
    return ApiKey.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApiKey>, I>>(object: I): ApiKey {
    const message = createBaseApiKey();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.key = object.key ?? "";
    message.user_id = object.user_id ?? "";
    message.description = object.description ?? "";
    message.scopes = object.scopes?.map((e) => e) || [];
    message.created_at = object.created_at ?? undefined;
    message.expires_at = object.expires_at ?? undefined;
    message.last_used_at = object.last_used_at ?? undefined;
    message.is_active = object.is_active ?? false;
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseApiKey_MetadataEntry(): ApiKey_MetadataEntry {
  return { key: "", value: "" };
}

export const ApiKey_MetadataEntry: MessageFns<ApiKey_MetadataEntry> = {
  encode(message: ApiKey_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApiKey_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApiKey_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApiKey_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ApiKey_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ApiKey_MetadataEntry>, I>>(base?: I): ApiKey_MetadataEntry {
    return ApiKey_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ApiKey_MetadataEntry>, I>>(object: I): ApiKey_MetadataEntry {
    const message = createBaseApiKey_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseCreateApiKeyRequest(): CreateApiKeyRequest {
  return { name: "", user_id: "", scopes: [], expires_at: undefined, metadata: {}, description: "" };
}

export const CreateApiKeyRequest: MessageFns<CreateApiKeyRequest> = {
  encode(message: CreateApiKeyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    for (const v of message.scopes) {
      writer.uint32(26).string(v!);
    }
    if (message.expires_at !== undefined) {
      Timestamp.encode(toTimestamp(message.expires_at), writer.uint32(34).fork()).join();
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      CreateApiKeyRequest_MetadataEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    if (message.description !== "") {
      writer.uint32(50).string(message.description);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateApiKeyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateApiKeyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.scopes.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.expires_at = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = CreateApiKeyRequest_MetadataEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.metadata[entry5.key] = entry5.value;
          }
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateApiKeyRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "",
      scopes: globalThis.Array.isArray(object?.scopes) ? object.scopes.map((e: any) => globalThis.String(e)) : [],
      expires_at: isSet(object.expires_at) ? fromJsonTimestamp(object.expires_at) : undefined,
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      description: isSet(object.description) ? globalThis.String(object.description) : "",
    };
  },

  toJSON(message: CreateApiKeyRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    if (message.scopes?.length) {
      obj.scopes = message.scopes;
    }
    if (message.expires_at !== undefined) {
      obj.expires_at = message.expires_at.toISOString();
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateApiKeyRequest>, I>>(base?: I): CreateApiKeyRequest {
    return CreateApiKeyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateApiKeyRequest>, I>>(object: I): CreateApiKeyRequest {
    const message = createBaseCreateApiKeyRequest();
    message.name = object.name ?? "";
    message.user_id = object.user_id ?? "";
    message.scopes = object.scopes?.map((e) => e) || [];
    message.expires_at = object.expires_at ?? undefined;
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.description = object.description ?? "";
    return message;
  },
};

function createBaseCreateApiKeyRequest_MetadataEntry(): CreateApiKeyRequest_MetadataEntry {
  return { key: "", value: "" };
}

export const CreateApiKeyRequest_MetadataEntry: MessageFns<CreateApiKeyRequest_MetadataEntry> = {
  encode(message: CreateApiKeyRequest_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateApiKeyRequest_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateApiKeyRequest_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateApiKeyRequest_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: CreateApiKeyRequest_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateApiKeyRequest_MetadataEntry>, I>>(
    base?: I,
  ): CreateApiKeyRequest_MetadataEntry {
    return CreateApiKeyRequest_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateApiKeyRequest_MetadataEntry>, I>>(
    object: I,
  ): CreateApiKeyRequest_MetadataEntry {
    const message = createBaseCreateApiKeyRequest_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseCreateApiKeyResponse(): CreateApiKeyResponse {
  return { api_key: undefined, raw_key: "" };
}

export const CreateApiKeyResponse: MessageFns<CreateApiKeyResponse> = {
  encode(message: CreateApiKeyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.api_key !== undefined) {
      ApiKey.encode(message.api_key, writer.uint32(10).fork()).join();
    }
    if (message.raw_key !== "") {
      writer.uint32(18).string(message.raw_key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateApiKeyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateApiKeyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.api_key = ApiKey.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.raw_key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateApiKeyResponse {
    return {
      api_key: isSet(object.api_key) ? ApiKey.fromJSON(object.api_key) : undefined,
      raw_key: isSet(object.raw_key) ? globalThis.String(object.raw_key) : "",
    };
  },

  toJSON(message: CreateApiKeyResponse): unknown {
    const obj: any = {};
    if (message.api_key !== undefined) {
      obj.api_key = ApiKey.toJSON(message.api_key);
    }
    if (message.raw_key !== "") {
      obj.raw_key = message.raw_key;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateApiKeyResponse>, I>>(base?: I): CreateApiKeyResponse {
    return CreateApiKeyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateApiKeyResponse>, I>>(object: I): CreateApiKeyResponse {
    const message = createBaseCreateApiKeyResponse();
    message.api_key = (object.api_key !== undefined && object.api_key !== null)
      ? ApiKey.fromPartial(object.api_key)
      : undefined;
    message.raw_key = object.raw_key ?? "";
    return message;
  },
};

function createBaseListApiKeysRequest(): ListApiKeysRequest {
  return { user_id: "", page: 0, limit: 0, include_inactive: false };
}

export const ListApiKeysRequest: MessageFns<ListApiKeysRequest> = {
  encode(message: ListApiKeysRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user_id !== "") {
      writer.uint32(10).string(message.user_id);
    }
    if (message.page !== 0) {
      writer.uint32(16).int32(message.page);
    }
    if (message.limit !== 0) {
      writer.uint32(24).int32(message.limit);
    }
    if (message.include_inactive !== false) {
      writer.uint32(32).bool(message.include_inactive);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListApiKeysRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListApiKeysRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.include_inactive = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListApiKeysRequest {
    return {
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "",
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      include_inactive: isSet(object.include_inactive) ? globalThis.Boolean(object.include_inactive) : false,
    };
  },

  toJSON(message: ListApiKeysRequest): unknown {
    const obj: any = {};
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.include_inactive !== false) {
      obj.include_inactive = message.include_inactive;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListApiKeysRequest>, I>>(base?: I): ListApiKeysRequest {
    return ListApiKeysRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListApiKeysRequest>, I>>(object: I): ListApiKeysRequest {
    const message = createBaseListApiKeysRequest();
    message.user_id = object.user_id ?? "";
    message.page = object.page ?? 0;
    message.limit = object.limit ?? 0;
    message.include_inactive = object.include_inactive ?? false;
    return message;
  },
};

function createBaseListApiKeysResponse(): ListApiKeysResponse {
  return { api_keys: [], total: 0, page: 0, limit: 0 };
}

export const ListApiKeysResponse: MessageFns<ListApiKeysResponse> = {
  encode(message: ListApiKeysResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.api_keys) {
      ApiKey.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.total !== 0) {
      writer.uint32(16).int32(message.total);
    }
    if (message.page !== 0) {
      writer.uint32(24).int32(message.page);
    }
    if (message.limit !== 0) {
      writer.uint32(32).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListApiKeysResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListApiKeysResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.api_keys.push(ApiKey.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListApiKeysResponse {
    return {
      api_keys: globalThis.Array.isArray(object?.api_keys) ? object.api_keys.map((e: any) => ApiKey.fromJSON(e)) : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: ListApiKeysResponse): unknown {
    const obj: any = {};
    if (message.api_keys?.length) {
      obj.api_keys = message.api_keys.map((e) => ApiKey.toJSON(e));
    }
    if (message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    if (message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListApiKeysResponse>, I>>(base?: I): ListApiKeysResponse {
    return ListApiKeysResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListApiKeysResponse>, I>>(object: I): ListApiKeysResponse {
    const message = createBaseListApiKeysResponse();
    message.api_keys = object.api_keys?.map((e) => ApiKey.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    message.page = object.page ?? 0;
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseGetApiKeyRequest(): GetApiKeyRequest {
  return { id: "" };
}

export const GetApiKeyRequest: MessageFns<GetApiKeyRequest> = {
  encode(message: GetApiKeyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetApiKeyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetApiKeyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetApiKeyRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetApiKeyRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetApiKeyRequest>, I>>(base?: I): GetApiKeyRequest {
    return GetApiKeyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetApiKeyRequest>, I>>(object: I): GetApiKeyRequest {
    const message = createBaseGetApiKeyRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseUpdateApiKeyRequest(): UpdateApiKeyRequest {
  return { id: "", name: "", scopes: [], expires_at: undefined, is_active: false, metadata: {} };
}

export const UpdateApiKeyRequest: MessageFns<UpdateApiKeyRequest> = {
  encode(message: UpdateApiKeyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    for (const v of message.scopes) {
      writer.uint32(26).string(v!);
    }
    if (message.expires_at !== undefined) {
      Timestamp.encode(toTimestamp(message.expires_at), writer.uint32(34).fork()).join();
    }
    if (message.is_active !== false) {
      writer.uint32(40).bool(message.is_active);
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      UpdateApiKeyRequest_MetadataEntry.encode({ key: key as any, value }, writer.uint32(50).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateApiKeyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateApiKeyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.scopes.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.expires_at = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.is_active = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          const entry6 = UpdateApiKeyRequest_MetadataEntry.decode(reader, reader.uint32());
          if (entry6.value !== undefined) {
            message.metadata[entry6.key] = entry6.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateApiKeyRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      scopes: globalThis.Array.isArray(object?.scopes) ? object.scopes.map((e: any) => globalThis.String(e)) : [],
      expires_at: isSet(object.expires_at) ? fromJsonTimestamp(object.expires_at) : undefined,
      is_active: isSet(object.is_active) ? globalThis.Boolean(object.is_active) : false,
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: UpdateApiKeyRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.scopes?.length) {
      obj.scopes = message.scopes;
    }
    if (message.expires_at !== undefined) {
      obj.expires_at = message.expires_at.toISOString();
    }
    if (message.is_active !== false) {
      obj.is_active = message.is_active;
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateApiKeyRequest>, I>>(base?: I): UpdateApiKeyRequest {
    return UpdateApiKeyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateApiKeyRequest>, I>>(object: I): UpdateApiKeyRequest {
    const message = createBaseUpdateApiKeyRequest();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.scopes = object.scopes?.map((e) => e) || [];
    message.expires_at = object.expires_at ?? undefined;
    message.is_active = object.is_active ?? false;
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseUpdateApiKeyRequest_MetadataEntry(): UpdateApiKeyRequest_MetadataEntry {
  return { key: "", value: "" };
}

export const UpdateApiKeyRequest_MetadataEntry: MessageFns<UpdateApiKeyRequest_MetadataEntry> = {
  encode(message: UpdateApiKeyRequest_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateApiKeyRequest_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateApiKeyRequest_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateApiKeyRequest_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: UpdateApiKeyRequest_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateApiKeyRequest_MetadataEntry>, I>>(
    base?: I,
  ): UpdateApiKeyRequest_MetadataEntry {
    return UpdateApiKeyRequest_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateApiKeyRequest_MetadataEntry>, I>>(
    object: I,
  ): UpdateApiKeyRequest_MetadataEntry {
    const message = createBaseUpdateApiKeyRequest_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseDeleteApiKeyRequest(): DeleteApiKeyRequest {
  return { id: "" };
}

export const DeleteApiKeyRequest: MessageFns<DeleteApiKeyRequest> = {
  encode(message: DeleteApiKeyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteApiKeyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteApiKeyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteApiKeyRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: DeleteApiKeyRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteApiKeyRequest>, I>>(base?: I): DeleteApiKeyRequest {
    return DeleteApiKeyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteApiKeyRequest>, I>>(object: I): DeleteApiKeyRequest {
    const message = createBaseDeleteApiKeyRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseValidateApiKeyRequest(): ValidateApiKeyRequest {
  return { api_key: "", required_scopes: [] };
}

export const ValidateApiKeyRequest: MessageFns<ValidateApiKeyRequest> = {
  encode(message: ValidateApiKeyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.api_key !== "") {
      writer.uint32(10).string(message.api_key);
    }
    for (const v of message.required_scopes) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateApiKeyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateApiKeyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.api_key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.required_scopes.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateApiKeyRequest {
    return {
      api_key: isSet(object.api_key) ? globalThis.String(object.api_key) : "",
      required_scopes: globalThis.Array.isArray(object?.required_scopes)
        ? object.required_scopes.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: ValidateApiKeyRequest): unknown {
    const obj: any = {};
    if (message.api_key !== "") {
      obj.api_key = message.api_key;
    }
    if (message.required_scopes?.length) {
      obj.required_scopes = message.required_scopes;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateApiKeyRequest>, I>>(base?: I): ValidateApiKeyRequest {
    return ValidateApiKeyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateApiKeyRequest>, I>>(object: I): ValidateApiKeyRequest {
    const message = createBaseValidateApiKeyRequest();
    message.api_key = object.api_key ?? "";
    message.required_scopes = object.required_scopes?.map((e) => e) || [];
    return message;
  },
};

function createBaseValidateApiKeyResponse(): ValidateApiKeyResponse {
  return { is_valid: false, api_key: undefined, error_message: "" };
}

export const ValidateApiKeyResponse: MessageFns<ValidateApiKeyResponse> = {
  encode(message: ValidateApiKeyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.is_valid !== false) {
      writer.uint32(8).bool(message.is_valid);
    }
    if (message.api_key !== undefined) {
      ApiKey.encode(message.api_key, writer.uint32(18).fork()).join();
    }
    if (message.error_message !== "") {
      writer.uint32(26).string(message.error_message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateApiKeyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateApiKeyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.is_valid = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.api_key = ApiKey.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.error_message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateApiKeyResponse {
    return {
      is_valid: isSet(object.is_valid) ? globalThis.Boolean(object.is_valid) : false,
      api_key: isSet(object.api_key) ? ApiKey.fromJSON(object.api_key) : undefined,
      error_message: isSet(object.error_message) ? globalThis.String(object.error_message) : "",
    };
  },

  toJSON(message: ValidateApiKeyResponse): unknown {
    const obj: any = {};
    if (message.is_valid !== false) {
      obj.is_valid = message.is_valid;
    }
    if (message.api_key !== undefined) {
      obj.api_key = ApiKey.toJSON(message.api_key);
    }
    if (message.error_message !== "") {
      obj.error_message = message.error_message;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateApiKeyResponse>, I>>(base?: I): ValidateApiKeyResponse {
    return ValidateApiKeyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateApiKeyResponse>, I>>(object: I): ValidateApiKeyResponse {
    const message = createBaseValidateApiKeyResponse();
    message.is_valid = object.is_valid ?? false;
    message.api_key = (object.api_key !== undefined && object.api_key !== null)
      ? ApiKey.fromPartial(object.api_key)
      : undefined;
    message.error_message = object.error_message ?? "";
    return message;
  },
};

function createBaseRotateApiKeyRequest(): RotateApiKeyRequest {
  return { id: "" };
}

export const RotateApiKeyRequest: MessageFns<RotateApiKeyRequest> = {
  encode(message: RotateApiKeyRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RotateApiKeyRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRotateApiKeyRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RotateApiKeyRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: RotateApiKeyRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RotateApiKeyRequest>, I>>(base?: I): RotateApiKeyRequest {
    return RotateApiKeyRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RotateApiKeyRequest>, I>>(object: I): RotateApiKeyRequest {
    const message = createBaseRotateApiKeyRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseRotateApiKeyResponse(): RotateApiKeyResponse {
  return { api_key: undefined, raw_key: "" };
}

export const RotateApiKeyResponse: MessageFns<RotateApiKeyResponse> = {
  encode(message: RotateApiKeyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.api_key !== undefined) {
      ApiKey.encode(message.api_key, writer.uint32(10).fork()).join();
    }
    if (message.raw_key !== "") {
      writer.uint32(18).string(message.raw_key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RotateApiKeyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRotateApiKeyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.api_key = ApiKey.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.raw_key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RotateApiKeyResponse {
    return {
      api_key: isSet(object.api_key) ? ApiKey.fromJSON(object.api_key) : undefined,
      raw_key: isSet(object.raw_key) ? globalThis.String(object.raw_key) : "",
    };
  },

  toJSON(message: RotateApiKeyResponse): unknown {
    const obj: any = {};
    if (message.api_key !== undefined) {
      obj.api_key = ApiKey.toJSON(message.api_key);
    }
    if (message.raw_key !== "") {
      obj.raw_key = message.raw_key;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RotateApiKeyResponse>, I>>(base?: I): RotateApiKeyResponse {
    return RotateApiKeyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RotateApiKeyResponse>, I>>(object: I): RotateApiKeyResponse {
    const message = createBaseRotateApiKeyResponse();
    message.api_key = (object.api_key !== undefined && object.api_key !== null)
      ? ApiKey.fromPartial(object.api_key)
      : undefined;
    message.raw_key = object.raw_key ?? "";
    return message;
  },
};

/** API Key 管理服务 */
export interface ApiKeyService {
  /** 创建新的 API Key */
  CreateApiKey(request: CreateApiKeyRequest): Promise<CreateApiKeyResponse>;
  /** 列出 API Keys */
  ListApiKeys(request: ListApiKeysRequest): Promise<ListApiKeysResponse>;
  /** 获取单个 API Key */
  GetApiKey(request: GetApiKeyRequest): Promise<ApiKey>;
  /** 更新 API Key */
  UpdateApiKey(request: UpdateApiKeyRequest): Promise<ApiKey>;
  /** 删除 API Key */
  DeleteApiKey(request: DeleteApiKeyRequest): Promise<Empty>;
  /** 验证 API Key */
  ValidateApiKey(request: ValidateApiKeyRequest): Promise<ValidateApiKeyResponse>;
  /** 轮换 API Key（生成新密钥值，停用旧密钥） */
  RotateApiKey(request: RotateApiKeyRequest): Promise<RotateApiKeyResponse>;
}

export const ApiKeyServiceServiceName = "stew.api.v1.ApiKeyService";
export class ApiKeyServiceClientImpl implements ApiKeyService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || ApiKeyServiceServiceName;
    this.rpc = rpc;
    this.CreateApiKey = this.CreateApiKey.bind(this);
    this.ListApiKeys = this.ListApiKeys.bind(this);
    this.GetApiKey = this.GetApiKey.bind(this);
    this.UpdateApiKey = this.UpdateApiKey.bind(this);
    this.DeleteApiKey = this.DeleteApiKey.bind(this);
    this.ValidateApiKey = this.ValidateApiKey.bind(this);
    this.RotateApiKey = this.RotateApiKey.bind(this);
  }
  CreateApiKey(request: CreateApiKeyRequest): Promise<CreateApiKeyResponse> {
    const data = CreateApiKeyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateApiKey", data);
    return promise.then((data) => CreateApiKeyResponse.decode(new BinaryReader(data)));
  }

  ListApiKeys(request: ListApiKeysRequest): Promise<ListApiKeysResponse> {
    const data = ListApiKeysRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListApiKeys", data);
    return promise.then((data) => ListApiKeysResponse.decode(new BinaryReader(data)));
  }

  GetApiKey(request: GetApiKeyRequest): Promise<ApiKey> {
    const data = GetApiKeyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetApiKey", data);
    return promise.then((data) => ApiKey.decode(new BinaryReader(data)));
  }

  UpdateApiKey(request: UpdateApiKeyRequest): Promise<ApiKey> {
    const data = UpdateApiKeyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateApiKey", data);
    return promise.then((data) => ApiKey.decode(new BinaryReader(data)));
  }

  DeleteApiKey(request: DeleteApiKeyRequest): Promise<Empty> {
    const data = DeleteApiKeyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeleteApiKey", data);
    return promise.then((data) => Empty.decode(new BinaryReader(data)));
  }

  ValidateApiKey(request: ValidateApiKeyRequest): Promise<ValidateApiKeyResponse> {
    const data = ValidateApiKeyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ValidateApiKey", data);
    return promise.then((data) => ValidateApiKeyResponse.decode(new BinaryReader(data)));
  }

  RotateApiKey(request: RotateApiKeyRequest): Promise<RotateApiKeyResponse> {
    const data = RotateApiKeyRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "RotateApiKey", data);
    return promise.then((data) => RotateApiKeyResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
