// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.21.12
// source: authentication.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Empty } from "./google/protobuf/empty";
import { ClientContext } from "./stew/api/v1/context";
import { RedirectResponse } from "./stew/api/v1/web";
import { User } from "./user";

export const protobufPackage = "stew.api.v1";

export interface OpenIDConnectCallbackRequest {
  code: string;
  state: string;
  nonce: string;
  callback: string;
  session_id: string;
}

export interface LoginRequest {
  callback: string;
}

export interface LoginCallbackResponse {
  user: User | undefined;
  token: string;
}

export interface LogoutRequest {
  callback: string;
  token: string;
  session_id: string;
}

export interface LogoutCallbackRequest {
  state: string;
  callback: string;
}

export interface AuthServiceUris {
  login_url: string;
  logout_url: string;
}

/** ===== Session Management Messages ===== */
export interface GetCurrentUserRequest {
}

export interface CurrentUserResponse {
  user: User | undefined;
  session_id: string;
  expires_at: number;
}

export interface ValidateSessionRequest {
  session_id: string;
}

export interface ValidateSessionResponse {
  valid: boolean;
  user_id: string;
  expires_at: number;
}

export interface RefreshTokenRequest {
  session_id: string;
}

export interface RefreshTokenResponse {
  access_token: string;
  expires_in: number;
}

function createBaseOpenIDConnectCallbackRequest(): OpenIDConnectCallbackRequest {
  return { code: "", state: "", nonce: "", callback: "", session_id: "" };
}

export const OpenIDConnectCallbackRequest: MessageFns<OpenIDConnectCallbackRequest> = {
  encode(message: OpenIDConnectCallbackRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.state !== "") {
      writer.uint32(18).string(message.state);
    }
    if (message.nonce !== "") {
      writer.uint32(42).string(message.nonce);
    }
    if (message.callback !== "") {
      writer.uint32(26).string(message.callback);
    }
    if (message.session_id !== "") {
      writer.uint32(34).string(message.session_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OpenIDConnectCallbackRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOpenIDConnectCallbackRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.nonce = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.callback = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OpenIDConnectCallbackRequest {
    return {
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      state: isSet(object.state) ? globalThis.String(object.state) : "",
      nonce: isSet(object.nonce) ? globalThis.String(object.nonce) : "",
      callback: isSet(object.callback) ? globalThis.String(object.callback) : "",
      session_id: isSet(object.session_id) ? globalThis.String(object.session_id) : "",
    };
  },

  toJSON(message: OpenIDConnectCallbackRequest): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.state !== "") {
      obj.state = message.state;
    }
    if (message.nonce !== "") {
      obj.nonce = message.nonce;
    }
    if (message.callback !== "") {
      obj.callback = message.callback;
    }
    if (message.session_id !== "") {
      obj.session_id = message.session_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OpenIDConnectCallbackRequest>, I>>(base?: I): OpenIDConnectCallbackRequest {
    return OpenIDConnectCallbackRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OpenIDConnectCallbackRequest>, I>>(object: I): OpenIDConnectCallbackRequest {
    const message = createBaseOpenIDConnectCallbackRequest();
    message.code = object.code ?? "";
    message.state = object.state ?? "";
    message.nonce = object.nonce ?? "";
    message.callback = object.callback ?? "";
    message.session_id = object.session_id ?? "";
    return message;
  },
};

function createBaseLoginRequest(): LoginRequest {
  return { callback: "" };
}

export const LoginRequest: MessageFns<LoginRequest> = {
  encode(message: LoginRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callback !== "") {
      writer.uint32(10).string(message.callback);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callback = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginRequest {
    return { callback: isSet(object.callback) ? globalThis.String(object.callback) : "" };
  },

  toJSON(message: LoginRequest): unknown {
    const obj: any = {};
    if (message.callback !== "") {
      obj.callback = message.callback;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginRequest>, I>>(base?: I): LoginRequest {
    return LoginRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginRequest>, I>>(object: I): LoginRequest {
    const message = createBaseLoginRequest();
    message.callback = object.callback ?? "";
    return message;
  },
};

function createBaseLoginCallbackResponse(): LoginCallbackResponse {
  return { user: undefined, token: "" };
}

export const LoginCallbackResponse: MessageFns<LoginCallbackResponse> = {
  encode(message: LoginCallbackResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(18).fork()).join();
    }
    if (message.token !== "") {
      writer.uint32(10).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginCallbackResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginCallbackResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginCallbackResponse {
    return {
      user: isSet(object.user) ? User.fromJSON(object.user) : undefined,
      token: isSet(object.token) ? globalThis.String(object.token) : "",
    };
  },

  toJSON(message: LoginCallbackResponse): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = User.toJSON(message.user);
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginCallbackResponse>, I>>(base?: I): LoginCallbackResponse {
    return LoginCallbackResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginCallbackResponse>, I>>(object: I): LoginCallbackResponse {
    const message = createBaseLoginCallbackResponse();
    message.user = (object.user !== undefined && object.user !== null) ? User.fromPartial(object.user) : undefined;
    message.token = object.token ?? "";
    return message;
  },
};

function createBaseLogoutRequest(): LogoutRequest {
  return { callback: "", token: "", session_id: "" };
}

export const LogoutRequest: MessageFns<LogoutRequest> = {
  encode(message: LogoutRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.callback !== "") {
      writer.uint32(10).string(message.callback);
    }
    if (message.token !== "") {
      writer.uint32(18).string(message.token);
    }
    if (message.session_id !== "") {
      writer.uint32(26).string(message.session_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogoutRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogoutRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callback = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.token = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogoutRequest {
    return {
      callback: isSet(object.callback) ? globalThis.String(object.callback) : "",
      token: isSet(object.token) ? globalThis.String(object.token) : "",
      session_id: isSet(object.session_id) ? globalThis.String(object.session_id) : "",
    };
  },

  toJSON(message: LogoutRequest): unknown {
    const obj: any = {};
    if (message.callback !== "") {
      obj.callback = message.callback;
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    if (message.session_id !== "") {
      obj.session_id = message.session_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogoutRequest>, I>>(base?: I): LogoutRequest {
    return LogoutRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogoutRequest>, I>>(object: I): LogoutRequest {
    const message = createBaseLogoutRequest();
    message.callback = object.callback ?? "";
    message.token = object.token ?? "";
    message.session_id = object.session_id ?? "";
    return message;
  },
};

function createBaseLogoutCallbackRequest(): LogoutCallbackRequest {
  return { state: "", callback: "" };
}

export const LogoutCallbackRequest: MessageFns<LogoutCallbackRequest> = {
  encode(message: LogoutCallbackRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.state !== "") {
      writer.uint32(18).string(message.state);
    }
    if (message.callback !== "") {
      writer.uint32(10).string(message.callback);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogoutCallbackRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogoutCallbackRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.callback = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogoutCallbackRequest {
    return {
      state: isSet(object.token)
        ? globalThis.String(object.token)
        : isSet(object.state)
        ? globalThis.String(object.state)
        : "",
      callback: isSet(object.callback) ? globalThis.String(object.callback) : "",
    };
  },

  toJSON(message: LogoutCallbackRequest): unknown {
    const obj: any = {};
    if (message.state !== "") {
      obj.token = message.state;
    }
    if (message.callback !== "") {
      obj.callback = message.callback;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogoutCallbackRequest>, I>>(base?: I): LogoutCallbackRequest {
    return LogoutCallbackRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogoutCallbackRequest>, I>>(object: I): LogoutCallbackRequest {
    const message = createBaseLogoutCallbackRequest();
    message.state = object.state ?? "";
    message.callback = object.callback ?? "";
    return message;
  },
};

function createBaseAuthServiceUris(): AuthServiceUris {
  return { login_url: "", logout_url: "" };
}

export const AuthServiceUris: MessageFns<AuthServiceUris> = {
  encode(message: AuthServiceUris, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.login_url !== "") {
      writer.uint32(10).string(message.login_url);
    }
    if (message.logout_url !== "") {
      writer.uint32(18).string(message.logout_url);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthServiceUris {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthServiceUris();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.login_url = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.logout_url = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthServiceUris {
    return {
      login_url: isSet(object.login_url) ? globalThis.String(object.login_url) : "",
      logout_url: isSet(object.logout_url) ? globalThis.String(object.logout_url) : "",
    };
  },

  toJSON(message: AuthServiceUris): unknown {
    const obj: any = {};
    if (message.login_url !== "") {
      obj.login_url = message.login_url;
    }
    if (message.logout_url !== "") {
      obj.logout_url = message.logout_url;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthServiceUris>, I>>(base?: I): AuthServiceUris {
    return AuthServiceUris.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthServiceUris>, I>>(object: I): AuthServiceUris {
    const message = createBaseAuthServiceUris();
    message.login_url = object.login_url ?? "";
    message.logout_url = object.logout_url ?? "";
    return message;
  },
};

function createBaseGetCurrentUserRequest(): GetCurrentUserRequest {
  return {};
}

export const GetCurrentUserRequest: MessageFns<GetCurrentUserRequest> = {
  encode(_: GetCurrentUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetCurrentUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetCurrentUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetCurrentUserRequest {
    return {};
  },

  toJSON(_: GetCurrentUserRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetCurrentUserRequest>, I>>(base?: I): GetCurrentUserRequest {
    return GetCurrentUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetCurrentUserRequest>, I>>(_: I): GetCurrentUserRequest {
    const message = createBaseGetCurrentUserRequest();
    return message;
  },
};

function createBaseCurrentUserResponse(): CurrentUserResponse {
  return { user: undefined, session_id: "", expires_at: 0 };
}

export const CurrentUserResponse: MessageFns<CurrentUserResponse> = {
  encode(message: CurrentUserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(10).fork()).join();
    }
    if (message.session_id !== "") {
      writer.uint32(18).string(message.session_id);
    }
    if (message.expires_at !== 0) {
      writer.uint32(24).int64(message.expires_at);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CurrentUserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCurrentUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.expires_at = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CurrentUserResponse {
    return {
      user: isSet(object.user) ? User.fromJSON(object.user) : undefined,
      session_id: isSet(object.session_id) ? globalThis.String(object.session_id) : "",
      expires_at: isSet(object.expires_at) ? globalThis.Number(object.expires_at) : 0,
    };
  },

  toJSON(message: CurrentUserResponse): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = User.toJSON(message.user);
    }
    if (message.session_id !== "") {
      obj.session_id = message.session_id;
    }
    if (message.expires_at !== 0) {
      obj.expires_at = Math.round(message.expires_at);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CurrentUserResponse>, I>>(base?: I): CurrentUserResponse {
    return CurrentUserResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CurrentUserResponse>, I>>(object: I): CurrentUserResponse {
    const message = createBaseCurrentUserResponse();
    message.user = (object.user !== undefined && object.user !== null) ? User.fromPartial(object.user) : undefined;
    message.session_id = object.session_id ?? "";
    message.expires_at = object.expires_at ?? 0;
    return message;
  },
};

function createBaseValidateSessionRequest(): ValidateSessionRequest {
  return { session_id: "" };
}

export const ValidateSessionRequest: MessageFns<ValidateSessionRequest> = {
  encode(message: ValidateSessionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session_id !== "") {
      writer.uint32(10).string(message.session_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateSessionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateSessionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateSessionRequest {
    return { session_id: isSet(object.session_id) ? globalThis.String(object.session_id) : "" };
  },

  toJSON(message: ValidateSessionRequest): unknown {
    const obj: any = {};
    if (message.session_id !== "") {
      obj.session_id = message.session_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateSessionRequest>, I>>(base?: I): ValidateSessionRequest {
    return ValidateSessionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateSessionRequest>, I>>(object: I): ValidateSessionRequest {
    const message = createBaseValidateSessionRequest();
    message.session_id = object.session_id ?? "";
    return message;
  },
};

function createBaseValidateSessionResponse(): ValidateSessionResponse {
  return { valid: false, user_id: "", expires_at: 0 };
}

export const ValidateSessionResponse: MessageFns<ValidateSessionResponse> = {
  encode(message: ValidateSessionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.valid !== false) {
      writer.uint32(8).bool(message.valid);
    }
    if (message.user_id !== "") {
      writer.uint32(18).string(message.user_id);
    }
    if (message.expires_at !== 0) {
      writer.uint32(24).int64(message.expires_at);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateSessionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateSessionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.valid = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.expires_at = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateSessionResponse {
    return {
      valid: isSet(object.valid) ? globalThis.Boolean(object.valid) : false,
      user_id: isSet(object.user_id) ? globalThis.String(object.user_id) : "",
      expires_at: isSet(object.expires_at) ? globalThis.Number(object.expires_at) : 0,
    };
  },

  toJSON(message: ValidateSessionResponse): unknown {
    const obj: any = {};
    if (message.valid !== false) {
      obj.valid = message.valid;
    }
    if (message.user_id !== "") {
      obj.user_id = message.user_id;
    }
    if (message.expires_at !== 0) {
      obj.expires_at = Math.round(message.expires_at);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateSessionResponse>, I>>(base?: I): ValidateSessionResponse {
    return ValidateSessionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateSessionResponse>, I>>(object: I): ValidateSessionResponse {
    const message = createBaseValidateSessionResponse();
    message.valid = object.valid ?? false;
    message.user_id = object.user_id ?? "";
    message.expires_at = object.expires_at ?? 0;
    return message;
  },
};

function createBaseRefreshTokenRequest(): RefreshTokenRequest {
  return { session_id: "" };
}

export const RefreshTokenRequest: MessageFns<RefreshTokenRequest> = {
  encode(message: RefreshTokenRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.session_id !== "") {
      writer.uint32(10).string(message.session_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefreshTokenRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefreshTokenRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.session_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RefreshTokenRequest {
    return { session_id: isSet(object.session_id) ? globalThis.String(object.session_id) : "" };
  },

  toJSON(message: RefreshTokenRequest): unknown {
    const obj: any = {};
    if (message.session_id !== "") {
      obj.session_id = message.session_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RefreshTokenRequest>, I>>(base?: I): RefreshTokenRequest {
    return RefreshTokenRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefreshTokenRequest>, I>>(object: I): RefreshTokenRequest {
    const message = createBaseRefreshTokenRequest();
    message.session_id = object.session_id ?? "";
    return message;
  },
};

function createBaseRefreshTokenResponse(): RefreshTokenResponse {
  return { access_token: "", expires_in: 0 };
}

export const RefreshTokenResponse: MessageFns<RefreshTokenResponse> = {
  encode(message: RefreshTokenResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.access_token !== "") {
      writer.uint32(10).string(message.access_token);
    }
    if (message.expires_in !== 0) {
      writer.uint32(16).int64(message.expires_in);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefreshTokenResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefreshTokenResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.access_token = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.expires_in = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RefreshTokenResponse {
    return {
      access_token: isSet(object.access_token) ? globalThis.String(object.access_token) : "",
      expires_in: isSet(object.expires_in) ? globalThis.Number(object.expires_in) : 0,
    };
  },

  toJSON(message: RefreshTokenResponse): unknown {
    const obj: any = {};
    if (message.access_token !== "") {
      obj.access_token = message.access_token;
    }
    if (message.expires_in !== 0) {
      obj.expires_in = Math.round(message.expires_in);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RefreshTokenResponse>, I>>(base?: I): RefreshTokenResponse {
    return RefreshTokenResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefreshTokenResponse>, I>>(object: I): RefreshTokenResponse {
    const message = createBaseRefreshTokenResponse();
    message.access_token = object.access_token ?? "";
    message.expires_in = object.expires_in ?? 0;
    return message;
  },
};

export interface AuthService {
  /** OpenID Connect callback endpoint */
  Callback(request: OpenIDConnectCallbackRequest): Promise<RedirectResponse>;
  Login(request: LoginRequest): Promise<RedirectResponse>;
  Context(request: ClientContext): Promise<Empty>;
  Logout(request: LogoutRequest): Promise<RedirectResponse>;
  LogoutCallback(request: OpenIDConnectCallbackRequest): Promise<RedirectResponse>;
  /** 获取当前登录用户信息（基于 session_id） */
  GetCurrentUser(request: GetCurrentUserRequest): Promise<CurrentUserResponse>;
  /** 验证 Session 有效性 */
  ValidateSession(request: ValidateSessionRequest): Promise<ValidateSessionResponse>;
  /** 刷新 Access Token */
  RefreshToken(request: RefreshTokenRequest): Promise<RefreshTokenResponse>;
}

export const AuthServiceServiceName = "stew.api.v1.AuthService";
export class AuthServiceClientImpl implements AuthService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || AuthServiceServiceName;
    this.rpc = rpc;
    this.Callback = this.Callback.bind(this);
    this.Login = this.Login.bind(this);
    this.Context = this.Context.bind(this);
    this.Logout = this.Logout.bind(this);
    this.LogoutCallback = this.LogoutCallback.bind(this);
    this.GetCurrentUser = this.GetCurrentUser.bind(this);
    this.ValidateSession = this.ValidateSession.bind(this);
    this.RefreshToken = this.RefreshToken.bind(this);
  }
  Callback(request: OpenIDConnectCallbackRequest): Promise<RedirectResponse> {
    const data = OpenIDConnectCallbackRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Callback", data);
    return promise.then((data) => RedirectResponse.decode(new BinaryReader(data)));
  }

  Login(request: LoginRequest): Promise<RedirectResponse> {
    const data = LoginRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Login", data);
    return promise.then((data) => RedirectResponse.decode(new BinaryReader(data)));
  }

  Context(request: ClientContext): Promise<Empty> {
    const data = ClientContext.encode(request).finish();
    const promise = this.rpc.request(this.service, "Context", data);
    return promise.then((data) => Empty.decode(new BinaryReader(data)));
  }

  Logout(request: LogoutRequest): Promise<RedirectResponse> {
    const data = LogoutRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "Logout", data);
    return promise.then((data) => RedirectResponse.decode(new BinaryReader(data)));
  }

  LogoutCallback(request: OpenIDConnectCallbackRequest): Promise<RedirectResponse> {
    const data = OpenIDConnectCallbackRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "LogoutCallback", data);
    return promise.then((data) => RedirectResponse.decode(new BinaryReader(data)));
  }

  GetCurrentUser(request: GetCurrentUserRequest): Promise<CurrentUserResponse> {
    const data = GetCurrentUserRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetCurrentUser", data);
    return promise.then((data) => CurrentUserResponse.decode(new BinaryReader(data)));
  }

  ValidateSession(request: ValidateSessionRequest): Promise<ValidateSessionResponse> {
    const data = ValidateSessionRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ValidateSession", data);
    return promise.then((data) => ValidateSessionResponse.decode(new BinaryReader(data)));
  }

  RefreshToken(request: RefreshTokenRequest): Promise<RefreshTokenResponse> {
    const data = RefreshTokenRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "RefreshToken", data);
    return promise.then((data) => RefreshTokenResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
