// Code generated by protoc-gen-ts_client. DO NOT EDIT.
// source: entitlement.proto
// Re-run `make ts` in the proto/ directory to regenerate this file.

import axios, { AxiosInstance, AxiosResponse } from 'axios';
import { APIResponse } from 'protobuf-typescript-client-gen';

// Import all required models
import { CancelPlanChangeRequest, CancelSubscriptionRequest, ChangePlanRequest, ChangePlanResponse, CheckFeatureRequest, CheckFeatureResponse, CheckQuotaRequest, CheckQuotaResponse, CreatePlanRequest, CreateSubscriptionRequest, DeletePlanFeatureRequest, DeletePlanQuotaRequest, DeletePlanRequest, DeleteSubscriptionRequest, EntitlementPlan, GetMyEntitlementRequest, GetPlanRequest, GetQuotaUsageRequest, GetSubscriptionBySubjectRequest, GetSubscriptionRequest, IncrementQuotaRequest, ListPlanChangesRequest, ListPlanChangesResponse, ListPlansRequest, ListPlansResponse, ListSubscriptionsRequest, ListSubscriptionsResponse, PlanChangeRecord, QuotaUsage, RenewSubscriptionsRequest, RenewSubscriptionsResponse, ResolvedEntitlementResponse, Subscription, UpdatePlanRequest, UpdateSubscriptionRequest, UpsertPlanFeatureRequest, UpsertPlanQuotaRequest } from './entitlement';
import { Empty } from './google/protobuf/empty';


export interface ClientConfig {
  baseUrl: string;
  timeout?: number;
}

export interface EmptyRequest {}

type ResponseWrapper<T> = { data?: T } | T;

/**
 * Convert Uint8Array to Base64 string
 */
function uint8ArrayToBase64(bytes: Uint8Array): string {
  if (typeof window !== 'undefined' && window.btoa) {
    // Browser environment
    const binary = Array.from(bytes).map(b => String.fromCharCode(b)).join('');
    return window.btoa(binary);
  } else {
    // Node.js environment
    return Buffer.from(bytes).toString('base64');
  }
}

/**
 * Recursively convert all Uint8Array fields to Base64 strings in request object
 */
function preprocessRequest(obj: any): any {
  if (!obj || typeof obj !== 'object') {
    return obj;
  }

  if (obj instanceof Uint8Array) {
    return uint8ArrayToBase64(obj);
  }

  if (Array.isArray(obj)) {
    return obj.map(item => preprocessRequest(item));
  }

  const result: any = {};
  for (const [key, value] of Object.entries(obj)) {
    result[key] = preprocessRequest(value);
  }
  return result;
}

/**
 * Type guard to check if a value is an APIResponse structure
 */
function isAPIResponse(data: any): data is APIResponse {
  return (
    data !== null &&
    typeof data === 'object' &&
    typeof data.code === 'number' &&
    'data' in data &&
    'message' in data
  );
}

export class V1Client {
  private client: AxiosInstance;
  private baseUrl: string;
  private accessToken: string | null = null;
  private tokenExpiry: Date | null = null;

  constructor(config: ClientConfig) {
    this.baseUrl = config.baseUrl.replace(/\/$/, '');
    
    this.client = axios.create({
      baseURL: this.baseUrl,
      timeout: config.timeout || 30000,
      headers: {
        'Content-Type': 'application/json',
      },
      withCredentials: true, // 允许发送 Cookie
    });

    // Add request interceptor for authentication
    this.client.interceptors.request.use(async (config) => {
      // 处理 Session-based 认证
      this.ensureSessionCookie();
      
      // 处理 Bearer token 认证
      this.accessToken = this.getToken();
      if (this.accessToken) {
        config.headers.Authorization = `Bearer ${this.accessToken}`;
      }
      return config;
    });

    // Add response interceptor to handle authentication failures
    this.client.interceptors.response.use(
      (response) => response,
      (error) => {
        // Check for authentication errors (401 Unauthorized)
        if (error.response && error.response.status === 401) {
          this.clearAuthState();
        }
        return Promise.reject(error);
      }
    );
  }

  /**
   * 手动登出 - 清除所有认证状态
   * 公共方法，允许用户主动调用
   */
  public logout(): void {
    this.clearAuthState();
  }

  /**
   * 清除所有认证状态
   * 当认证失败时调用，清除 localStorage、sessionStorage 和所有 Cookie
   */
  private clearAuthState(): void {
    // 仅在浏览器环境中执行
    if (typeof window === 'undefined') {
      return;
    }

    try {
      // 清除 localStorage 中的认证相关信息
      if (typeof localStorage !== 'undefined') {
        localStorage.removeItem('session_id');
        localStorage.removeItem('token');
        localStorage.removeItem('access_token');
        localStorage.removeItem('refresh_token');
        console.debug('[Auth] Cleared localStorage auth data');
      }

      // 清除 sessionStorage 中的认证相关信息
      if (typeof sessionStorage !== 'undefined') {
        sessionStorage.removeItem('session_id');
        sessionStorage.removeItem('token');
        sessionStorage.removeItem('access_token');
        sessionStorage.removeItem('refresh_token');
        console.debug('[Auth] Cleared sessionStorage auth data');
      }

      // 清除所有 Cookie
      if (typeof document !== 'undefined' && document.cookie) {
        const cookies = document.cookie.split(';');
        for (let cookie of cookies) {
          const [name] = cookie.trim().split('=');
          if (name) {
            // 删除 Cookie（设置过期时间为过去）
            // 尝试多种路径和域组合以确保删除
            document.cookie = `${name}=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;`;
            document.cookie = `${name}=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/; domain=${window.location.hostname};`;
            
            // 如果域名有子域，尝试删除父域的 Cookie
            const hostnameParts = window.location.hostname.split('.');
            if (hostnameParts.length > 2) {
              const parentDomain = hostnameParts.slice(-2).join('.');
              document.cookie = `${name}=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/; domain=.${parentDomain};`;
            }
          }
        }
        console.debug('[Auth] Cleared all cookies');
      }

      // 清除当前实例的 token
      this.accessToken = null;
      this.tokenExpiry = null;

      console.warn('[Auth] Authentication failed - all auth state cleared');
    } catch (error) {
      console.error('[Auth] Failed to clear auth state:', error);
    }
  }

  /**
   * 确保 session_id Cookie 已设置
   * 从 localStorage 读取 session_id，如果存在则设置到 Cookie
   */
  private ensureSessionCookie(): void {
    // 仅在浏览器环境中执行
    if (typeof window === 'undefined' || typeof document === 'undefined') {
      return;
    }

    try {
      // 从 localStorage 读取 session_id
      const sessionId = localStorage.getItem('session_id');
      
      if (sessionId) {
        // 检查 Cookie 中是否已存在 session_id
        const cookies = document.cookie.split(';');
        const hasSessionCookie = cookies.some(cookie => {
          const [name] = cookie.trim().split('=');
          return name === 'session_id';
        });

        // 如果 Cookie 中没有 session_id，则设置它
        if (!hasSessionCookie) {
          // 设置 Cookie（路径为 /，SameSite=Lax 以支持跨页面导航）
          document.cookie = `session_id=${sessionId}; path=/; SameSite=Lax`;
          console.debug('[Auth] Set session_id cookie from localStorage');
        }
      }
    } catch (error) {
      console.warn('[Auth] Failed to sync session_id to cookie:', error);
    }
  }

  /**
   * 从 localStorage/Cookie 获取 session_id
   */
  private getSessionId(): string | null {
    // 检查浏览器环境
    if (typeof window !== 'undefined') {
      // 优先从 localStorage 获取
      if (typeof localStorage !== 'undefined') {
        const sessionId = localStorage.getItem('session_id');
        if (sessionId) {
          return sessionId;
        }
      }
      
      // 从 Cookie 获取作为后备
      if (typeof document !== 'undefined' && document.cookie) {
        const cookies = document.cookie.split(';');
        for (let cookie of cookies) {
          const [name, value] = cookie.trim().split('=');
          if (name === 'session_id') {
            return decodeURIComponent(value);
          }
        }
      }
    }
    
    return null;
  }

private getToken(): string | null {
  // Check if we're in a browser environment
  if (typeof window !== 'undefined') {
    // Browser environment - use localStorage, sessionStorage, and cookies
    
    // 从localStorage获取token
    if (typeof localStorage !== 'undefined') {
      const token = localStorage.getItem('token') || localStorage.getItem('access_token');
      if (token) {
        return token;
      }
    }
    
    // 从sessionStorage获取token
    if (typeof sessionStorage !== 'undefined') {
      const sessionToken = sessionStorage.getItem('token') || sessionStorage.getItem('access_token');
      if (sessionToken) {
        return sessionToken;
      }
    }
    
    // 从cookie获取token（如果使用cookie存储）
    if (typeof document !== 'undefined' && document.cookie) {
      const cookies = document.cookie.split(';');
      for (let cookie of cookies) {
        const [name, value] = cookie.trim().split('=');
        if (name === 'token' || name === 'access_token') {
          return decodeURIComponent(value);
        }
      }
    }
  } else if (typeof process !== 'undefined' && process.env) {
    // Node.js environment - try to get token from environment variables
    return process.env.ACCESS_TOKEN || process.env.TOKEN || null;
  }
  
  return null;
}

  private async getAuthHeaders(): Promise<Record<string, string>> {
    this.accessToken = this.getToken();
    return this.accessToken ? { Authorization: `Bearer ${this.accessToken}` } : {};
  }

  // EntitlementService methods
  async create_plan(
    request: CreatePlanRequest,
    headers?: Record<string, string>
  ): Promise<EntitlementPlan> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/plans`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // POST/PUT/PATCH: pass data as second parameter
    //     // v1.0.1

    const response: AxiosResponse<any> = await this.client.post(
      url,
      processedRequest,
      { headers: requestHeaders }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return EntitlementPlan.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as EntitlementPlan:', userData);
        return EntitlementPlan.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as EntitlementPlan:', response.data);
      return EntitlementPlan.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as EntitlementPlan (non-wrapped):', response.data);
    return EntitlementPlan.fromJSON(response.data);
  }
  async get_plan(
    request: GetPlanRequest,
    headers?: Record<string, string>
  ): Promise<EntitlementPlan> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/plans/{business_id}/{plan_id}`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // GET/DELETE/HEAD/OPTIONS: pass params in config object
    const response: AxiosResponse<any> = await this.client.get(
      url,
      { 
        params: processedRequest,
        headers: requestHeaders 
      }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return EntitlementPlan.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as EntitlementPlan:', userData);
        return EntitlementPlan.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as EntitlementPlan:', response.data);
      return EntitlementPlan.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as EntitlementPlan (non-wrapped):', response.data);
    return EntitlementPlan.fromJSON(response.data);
  }
  async list_plans(
    request: ListPlansRequest,
    headers?: Record<string, string>
  ): Promise<ListPlansResponse> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/plans/{business_id}`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // GET/DELETE/HEAD/OPTIONS: pass params in config object
    const response: AxiosResponse<any> = await this.client.get(
      url,
      { 
        params: processedRequest,
        headers: requestHeaders 
      }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return ListPlansResponse.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as ListPlansResponse:', userData);
        return ListPlansResponse.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as ListPlansResponse:', response.data);
      return ListPlansResponse.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as ListPlansResponse (non-wrapped):', response.data);
    return ListPlansResponse.fromJSON(response.data);
  }
  async update_plan(
    request: UpdatePlanRequest,
    headers?: Record<string, string>
  ): Promise<EntitlementPlan> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/plans/{business_id}/{plan_id}`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // POST/PUT/PATCH: pass data as second parameter
    //     // v1.0.1

    const response: AxiosResponse<any> = await this.client.put(
      url,
      processedRequest,
      { headers: requestHeaders }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return EntitlementPlan.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as EntitlementPlan:', userData);
        return EntitlementPlan.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as EntitlementPlan:', response.data);
      return EntitlementPlan.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as EntitlementPlan (non-wrapped):', response.data);
    return EntitlementPlan.fromJSON(response.data);
  }
  async delete_plan(
    request: DeletePlanRequest,
    headers?: Record<string, string>
  ): Promise<Empty> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/plans/{business_id}/{plan_id}`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // GET/DELETE/HEAD/OPTIONS: pass params in config object
    const response: AxiosResponse<any> = await this.client.delete(
      url,
      { 
        params: processedRequest,
        headers: requestHeaders 
      }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return Empty.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as Empty:', userData);
        return Empty.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as Empty:', response.data);
      return Empty.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as Empty (non-wrapped):', response.data);
    return Empty.fromJSON(response.data);
  }
  async upsert_plan_feature(
    request: UpsertPlanFeatureRequest,
    headers?: Record<string, string>
  ): Promise<EntitlementPlan> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/plans/{business_id}/{plan_id}/features`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // POST/PUT/PATCH: pass data as second parameter
    //     // v1.0.1

    const response: AxiosResponse<any> = await this.client.put(
      url,
      processedRequest,
      { headers: requestHeaders }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return EntitlementPlan.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as EntitlementPlan:', userData);
        return EntitlementPlan.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as EntitlementPlan:', response.data);
      return EntitlementPlan.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as EntitlementPlan (non-wrapped):', response.data);
    return EntitlementPlan.fromJSON(response.data);
  }
  async delete_plan_feature(
    request: DeletePlanFeatureRequest,
    headers?: Record<string, string>
  ): Promise<EntitlementPlan> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/plans/{business_id}/{plan_id}/features/{feature_key}`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // GET/DELETE/HEAD/OPTIONS: pass params in config object
    const response: AxiosResponse<any> = await this.client.delete(
      url,
      { 
        params: processedRequest,
        headers: requestHeaders 
      }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return EntitlementPlan.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as EntitlementPlan:', userData);
        return EntitlementPlan.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as EntitlementPlan:', response.data);
      return EntitlementPlan.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as EntitlementPlan (non-wrapped):', response.data);
    return EntitlementPlan.fromJSON(response.data);
  }
  async upsert_plan_quota(
    request: UpsertPlanQuotaRequest,
    headers?: Record<string, string>
  ): Promise<EntitlementPlan> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/plans/{business_id}/{plan_id}/quotas`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // POST/PUT/PATCH: pass data as second parameter
    //     // v1.0.1

    const response: AxiosResponse<any> = await this.client.put(
      url,
      processedRequest,
      { headers: requestHeaders }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return EntitlementPlan.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as EntitlementPlan:', userData);
        return EntitlementPlan.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as EntitlementPlan:', response.data);
      return EntitlementPlan.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as EntitlementPlan (non-wrapped):', response.data);
    return EntitlementPlan.fromJSON(response.data);
  }
  async delete_plan_quota(
    request: DeletePlanQuotaRequest,
    headers?: Record<string, string>
  ): Promise<EntitlementPlan> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/plans/{business_id}/{plan_id}/quotas/{quota_key}`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // GET/DELETE/HEAD/OPTIONS: pass params in config object
    const response: AxiosResponse<any> = await this.client.delete(
      url,
      { 
        params: processedRequest,
        headers: requestHeaders 
      }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return EntitlementPlan.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as EntitlementPlan:', userData);
        return EntitlementPlan.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as EntitlementPlan:', response.data);
      return EntitlementPlan.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as EntitlementPlan (non-wrapped):', response.data);
    return EntitlementPlan.fromJSON(response.data);
  }
  async create_subscription(
    request: CreateSubscriptionRequest,
    headers?: Record<string, string>
  ): Promise<Subscription> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/subscriptions`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // POST/PUT/PATCH: pass data as second parameter
    //     // v1.0.1

    const response: AxiosResponse<any> = await this.client.post(
      url,
      processedRequest,
      { headers: requestHeaders }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return Subscription.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as Subscription:', userData);
        return Subscription.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as Subscription:', response.data);
      return Subscription.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as Subscription (non-wrapped):', response.data);
    return Subscription.fromJSON(response.data);
  }
  async get_subscription(
    request: GetSubscriptionRequest,
    headers?: Record<string, string>
  ): Promise<Subscription> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/subscriptions/{business_id}/{subscription_id}`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // GET/DELETE/HEAD/OPTIONS: pass params in config object
    const response: AxiosResponse<any> = await this.client.get(
      url,
      { 
        params: processedRequest,
        headers: requestHeaders 
      }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return Subscription.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as Subscription:', userData);
        return Subscription.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as Subscription:', response.data);
      return Subscription.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as Subscription (non-wrapped):', response.data);
    return Subscription.fromJSON(response.data);
  }
  async get_subscription_by_subject(
    request: GetSubscriptionBySubjectRequest,
    headers?: Record<string, string>
  ): Promise<Subscription> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/subscriptions/{business_id}/subject/{subject_id}`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // GET/DELETE/HEAD/OPTIONS: pass params in config object
    const response: AxiosResponse<any> = await this.client.get(
      url,
      { 
        params: processedRequest,
        headers: requestHeaders 
      }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return Subscription.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as Subscription:', userData);
        return Subscription.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as Subscription:', response.data);
      return Subscription.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as Subscription (non-wrapped):', response.data);
    return Subscription.fromJSON(response.data);
  }
  async update_subscription(
    request: UpdateSubscriptionRequest,
    headers?: Record<string, string>
  ): Promise<Subscription> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/subscriptions/{business_id}/{subscription_id}`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // POST/PUT/PATCH: pass data as second parameter
    //     // v1.0.1

    const response: AxiosResponse<any> = await this.client.put(
      url,
      processedRequest,
      { headers: requestHeaders }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return Subscription.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as Subscription:', userData);
        return Subscription.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as Subscription:', response.data);
      return Subscription.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as Subscription (non-wrapped):', response.data);
    return Subscription.fromJSON(response.data);
  }
  async cancel_subscription(
    request: CancelSubscriptionRequest,
    headers?: Record<string, string>
  ): Promise<Subscription> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/subscriptions/{business_id}/{subscription_id}/cancel`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // POST/PUT/PATCH: pass data as second parameter
    //     // v1.0.1

    const response: AxiosResponse<any> = await this.client.post(
      url,
      processedRequest,
      { headers: requestHeaders }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return Subscription.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as Subscription:', userData);
        return Subscription.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as Subscription:', response.data);
      return Subscription.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as Subscription (non-wrapped):', response.data);
    return Subscription.fromJSON(response.data);
  }
  async delete_subscription(
    request: DeleteSubscriptionRequest,
    headers?: Record<string, string>
  ): Promise<Empty> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/subscriptions/{business_id}/{subscription_id}`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // GET/DELETE/HEAD/OPTIONS: pass params in config object
    const response: AxiosResponse<any> = await this.client.delete(
      url,
      { 
        params: processedRequest,
        headers: requestHeaders 
      }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return Empty.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as Empty:', userData);
        return Empty.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as Empty:', response.data);
      return Empty.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as Empty (non-wrapped):', response.data);
    return Empty.fromJSON(response.data);
  }
  async list_subscriptions(
    request: ListSubscriptionsRequest,
    headers?: Record<string, string>
  ): Promise<ListSubscriptionsResponse> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/subscriptions/{business_id}`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // GET/DELETE/HEAD/OPTIONS: pass params in config object
    const response: AxiosResponse<any> = await this.client.get(
      url,
      { 
        params: processedRequest,
        headers: requestHeaders 
      }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return ListSubscriptionsResponse.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as ListSubscriptionsResponse:', userData);
        return ListSubscriptionsResponse.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as ListSubscriptionsResponse:', response.data);
      return ListSubscriptionsResponse.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as ListSubscriptionsResponse (non-wrapped):', response.data);
    return ListSubscriptionsResponse.fromJSON(response.data);
  }
  async renew_subscriptions(
    request: RenewSubscriptionsRequest,
    headers?: Record<string, string>
  ): Promise<RenewSubscriptionsResponse> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/subscriptions/renew`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // POST/PUT/PATCH: pass data as second parameter
    //     // v1.0.1

    const response: AxiosResponse<any> = await this.client.post(
      url,
      processedRequest,
      { headers: requestHeaders }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return RenewSubscriptionsResponse.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as RenewSubscriptionsResponse:', userData);
        return RenewSubscriptionsResponse.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as RenewSubscriptionsResponse:', response.data);
      return RenewSubscriptionsResponse.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as RenewSubscriptionsResponse (non-wrapped):', response.data);
    return RenewSubscriptionsResponse.fromJSON(response.data);
  }
  async get_quota_usage(
    request: GetQuotaUsageRequest,
    headers?: Record<string, string>
  ): Promise<QuotaUsage> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/quotas/{business_id}/{subject_id}/{quota_key}`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // GET/DELETE/HEAD/OPTIONS: pass params in config object
    const response: AxiosResponse<any> = await this.client.get(
      url,
      { 
        params: processedRequest,
        headers: requestHeaders 
      }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return QuotaUsage.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as QuotaUsage:', userData);
        return QuotaUsage.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as QuotaUsage:', response.data);
      return QuotaUsage.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as QuotaUsage (non-wrapped):', response.data);
    return QuotaUsage.fromJSON(response.data);
  }
  async increment_quota(
    request: IncrementQuotaRequest,
    headers?: Record<string, string>
  ): Promise<QuotaUsage> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/quotas/increment`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // POST/PUT/PATCH: pass data as second parameter
    //     // v1.0.1

    const response: AxiosResponse<any> = await this.client.post(
      url,
      processedRequest,
      { headers: requestHeaders }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return QuotaUsage.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as QuotaUsage:', userData);
        return QuotaUsage.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as QuotaUsage:', response.data);
      return QuotaUsage.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as QuotaUsage (non-wrapped):', response.data);
    return QuotaUsage.fromJSON(response.data);
  }
  async check_quota(
    request: CheckQuotaRequest,
    headers?: Record<string, string>
  ): Promise<CheckQuotaResponse> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/quotas/{business_id}/{subject_id}/{quota_key}/check`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // GET/DELETE/HEAD/OPTIONS: pass params in config object
    const response: AxiosResponse<any> = await this.client.get(
      url,
      { 
        params: processedRequest,
        headers: requestHeaders 
      }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return CheckQuotaResponse.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as CheckQuotaResponse:', userData);
        return CheckQuotaResponse.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as CheckQuotaResponse:', response.data);
      return CheckQuotaResponse.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as CheckQuotaResponse (non-wrapped):', response.data);
    return CheckQuotaResponse.fromJSON(response.data);
  }
  async get_my_entitlement(
    request: GetMyEntitlementRequest,
    headers?: Record<string, string>
  ): Promise<ResolvedEntitlementResponse> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/me/{business_id}/{subject_id}`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // GET/DELETE/HEAD/OPTIONS: pass params in config object
    const response: AxiosResponse<any> = await this.client.get(
      url,
      { 
        params: processedRequest,
        headers: requestHeaders 
      }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return ResolvedEntitlementResponse.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as ResolvedEntitlementResponse:', userData);
        return ResolvedEntitlementResponse.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as ResolvedEntitlementResponse:', response.data);
      return ResolvedEntitlementResponse.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as ResolvedEntitlementResponse (non-wrapped):', response.data);
    return ResolvedEntitlementResponse.fromJSON(response.data);
  }
  async check_feature(
    request: CheckFeatureRequest,
    headers?: Record<string, string>
  ): Promise<CheckFeatureResponse> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/me/{business_id}/{subject_id}/features/{feature_key}`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // GET/DELETE/HEAD/OPTIONS: pass params in config object
    const response: AxiosResponse<any> = await this.client.get(
      url,
      { 
        params: processedRequest,
        headers: requestHeaders 
      }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return CheckFeatureResponse.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as CheckFeatureResponse:', userData);
        return CheckFeatureResponse.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as CheckFeatureResponse:', response.data);
      return CheckFeatureResponse.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as CheckFeatureResponse (non-wrapped):', response.data);
    return CheckFeatureResponse.fromJSON(response.data);
  }
  async change_plan(
    request: ChangePlanRequest,
    headers?: Record<string, string>
  ): Promise<ChangePlanResponse> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/subscriptions/{business_id}/change-plan`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // POST/PUT/PATCH: pass data as second parameter
    //     // v1.0.1

    const response: AxiosResponse<any> = await this.client.post(
      url,
      processedRequest,
      { headers: requestHeaders }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return ChangePlanResponse.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as ChangePlanResponse:', userData);
        return ChangePlanResponse.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as ChangePlanResponse:', response.data);
      return ChangePlanResponse.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as ChangePlanResponse (non-wrapped):', response.data);
    return ChangePlanResponse.fromJSON(response.data);
  }
  async list_plan_changes(
    request: ListPlanChangesRequest,
    headers?: Record<string, string>
  ): Promise<ListPlanChangesResponse> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/subscriptions/{business_id}/plan-changes`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // GET/DELETE/HEAD/OPTIONS: pass params in config object
    const response: AxiosResponse<any> = await this.client.get(
      url,
      { 
        params: processedRequest,
        headers: requestHeaders 
      }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return ListPlanChangesResponse.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as ListPlanChangesResponse:', userData);
        return ListPlanChangesResponse.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as ListPlanChangesResponse:', response.data);
      return ListPlanChangesResponse.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as ListPlanChangesResponse (non-wrapped):', response.data);
    return ListPlanChangesResponse.fromJSON(response.data);
  }
  async cancel_plan_change(
    request: CancelPlanChangeRequest,
    headers?: Record<string, string>
  ): Promise<PlanChangeRecord> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/api/v1/entitlements/subscriptions/{business_id}/plan-changes/{change_id}:cancel`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // POST/PUT/PATCH: pass data as second parameter
    //     // v1.0.1

    const response: AxiosResponse<any> = await this.client.post(
      url,
      processedRequest,
      { headers: requestHeaders }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[EntitlementService] Extracting user from nested structure:', userData.user);
          return PlanChangeRecord.fromJSON(userData.user);
        }

        console.log('[EntitlementService] Using data directly as PlanChangeRecord:', userData);
        return PlanChangeRecord.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[EntitlementService] Using response.data directly as PlanChangeRecord:', response.data);
      return PlanChangeRecord.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[EntitlementService] Using response directly as PlanChangeRecord (non-wrapped):', response.data);
    return PlanChangeRecord.fromJSON(response.data);
  }
}