// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.21.12
// source: payment.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Struct } from "./google/protobuf/struct";

export const protobufPackage = "stew.api.v1";

export enum PaymentProviderKind {
  PAYMENT_PROVIDER_KIND_UNSPECIFIED = 0,
  PAYMENT_PROVIDER_KIND_STRIPE = 1,
  PAYMENT_PROVIDER_KIND_CREEM = 2,
  UNRECOGNIZED = -1,
}

export function paymentProviderKindFromJSON(object: any): PaymentProviderKind {
  switch (object) {
    case 0:
    case "PAYMENT_PROVIDER_KIND_UNSPECIFIED":
      return PaymentProviderKind.PAYMENT_PROVIDER_KIND_UNSPECIFIED;
    case 1:
    case "PAYMENT_PROVIDER_KIND_STRIPE":
      return PaymentProviderKind.PAYMENT_PROVIDER_KIND_STRIPE;
    case 2:
    case "PAYMENT_PROVIDER_KIND_CREEM":
      return PaymentProviderKind.PAYMENT_PROVIDER_KIND_CREEM;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PaymentProviderKind.UNRECOGNIZED;
  }
}

export function paymentProviderKindToJSON(object: PaymentProviderKind): string {
  switch (object) {
    case PaymentProviderKind.PAYMENT_PROVIDER_KIND_UNSPECIFIED:
      return "PAYMENT_PROVIDER_KIND_UNSPECIFIED";
    case PaymentProviderKind.PAYMENT_PROVIDER_KIND_STRIPE:
      return "PAYMENT_PROVIDER_KIND_STRIPE";
    case PaymentProviderKind.PAYMENT_PROVIDER_KIND_CREEM:
      return "PAYMENT_PROVIDER_KIND_CREEM";
    case PaymentProviderKind.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum PaymentOrderStatus {
  PAYMENT_ORDER_STATUS_UNSPECIFIED = 0,
  PAYMENT_ORDER_STATUS_PENDING = 1,
  PAYMENT_ORDER_STATUS_PAID = 2,
  PAYMENT_ORDER_STATUS_FAILED = 3,
  PAYMENT_ORDER_STATUS_REFUNDED = 4,
  PAYMENT_ORDER_STATUS_CANCELED = 5,
  PAYMENT_ORDER_STATUS_EXPIRED = 6,
  UNRECOGNIZED = -1,
}

export function paymentOrderStatusFromJSON(object: any): PaymentOrderStatus {
  switch (object) {
    case 0:
    case "PAYMENT_ORDER_STATUS_UNSPECIFIED":
      return PaymentOrderStatus.PAYMENT_ORDER_STATUS_UNSPECIFIED;
    case 1:
    case "PAYMENT_ORDER_STATUS_PENDING":
      return PaymentOrderStatus.PAYMENT_ORDER_STATUS_PENDING;
    case 2:
    case "PAYMENT_ORDER_STATUS_PAID":
      return PaymentOrderStatus.PAYMENT_ORDER_STATUS_PAID;
    case 3:
    case "PAYMENT_ORDER_STATUS_FAILED":
      return PaymentOrderStatus.PAYMENT_ORDER_STATUS_FAILED;
    case 4:
    case "PAYMENT_ORDER_STATUS_REFUNDED":
      return PaymentOrderStatus.PAYMENT_ORDER_STATUS_REFUNDED;
    case 5:
    case "PAYMENT_ORDER_STATUS_CANCELED":
      return PaymentOrderStatus.PAYMENT_ORDER_STATUS_CANCELED;
    case 6:
    case "PAYMENT_ORDER_STATUS_EXPIRED":
      return PaymentOrderStatus.PAYMENT_ORDER_STATUS_EXPIRED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PaymentOrderStatus.UNRECOGNIZED;
  }
}

export function paymentOrderStatusToJSON(object: PaymentOrderStatus): string {
  switch (object) {
    case PaymentOrderStatus.PAYMENT_ORDER_STATUS_UNSPECIFIED:
      return "PAYMENT_ORDER_STATUS_UNSPECIFIED";
    case PaymentOrderStatus.PAYMENT_ORDER_STATUS_PENDING:
      return "PAYMENT_ORDER_STATUS_PENDING";
    case PaymentOrderStatus.PAYMENT_ORDER_STATUS_PAID:
      return "PAYMENT_ORDER_STATUS_PAID";
    case PaymentOrderStatus.PAYMENT_ORDER_STATUS_FAILED:
      return "PAYMENT_ORDER_STATUS_FAILED";
    case PaymentOrderStatus.PAYMENT_ORDER_STATUS_REFUNDED:
      return "PAYMENT_ORDER_STATUS_REFUNDED";
    case PaymentOrderStatus.PAYMENT_ORDER_STATUS_CANCELED:
      return "PAYMENT_ORDER_STATUS_CANCELED";
    case PaymentOrderStatus.PAYMENT_ORDER_STATUS_EXPIRED:
      return "PAYMENT_ORDER_STATUS_EXPIRED";
    case PaymentOrderStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum PaymentBillingInterval {
  PAYMENT_BILLING_INTERVAL_UNSPECIFIED = 0,
  PAYMENT_BILLING_INTERVAL_ONE_TIME = 1,
  PAYMENT_BILLING_INTERVAL_MONTHLY = 2,
  PAYMENT_BILLING_INTERVAL_QUARTERLY = 3,
  PAYMENT_BILLING_INTERVAL_YEARLY = 4,
  UNRECOGNIZED = -1,
}

export function paymentBillingIntervalFromJSON(object: any): PaymentBillingInterval {
  switch (object) {
    case 0:
    case "PAYMENT_BILLING_INTERVAL_UNSPECIFIED":
      return PaymentBillingInterval.PAYMENT_BILLING_INTERVAL_UNSPECIFIED;
    case 1:
    case "PAYMENT_BILLING_INTERVAL_ONE_TIME":
      return PaymentBillingInterval.PAYMENT_BILLING_INTERVAL_ONE_TIME;
    case 2:
    case "PAYMENT_BILLING_INTERVAL_MONTHLY":
      return PaymentBillingInterval.PAYMENT_BILLING_INTERVAL_MONTHLY;
    case 3:
    case "PAYMENT_BILLING_INTERVAL_QUARTERLY":
      return PaymentBillingInterval.PAYMENT_BILLING_INTERVAL_QUARTERLY;
    case 4:
    case "PAYMENT_BILLING_INTERVAL_YEARLY":
      return PaymentBillingInterval.PAYMENT_BILLING_INTERVAL_YEARLY;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PaymentBillingInterval.UNRECOGNIZED;
  }
}

export function paymentBillingIntervalToJSON(object: PaymentBillingInterval): string {
  switch (object) {
    case PaymentBillingInterval.PAYMENT_BILLING_INTERVAL_UNSPECIFIED:
      return "PAYMENT_BILLING_INTERVAL_UNSPECIFIED";
    case PaymentBillingInterval.PAYMENT_BILLING_INTERVAL_ONE_TIME:
      return "PAYMENT_BILLING_INTERVAL_ONE_TIME";
    case PaymentBillingInterval.PAYMENT_BILLING_INTERVAL_MONTHLY:
      return "PAYMENT_BILLING_INTERVAL_MONTHLY";
    case PaymentBillingInterval.PAYMENT_BILLING_INTERVAL_QUARTERLY:
      return "PAYMENT_BILLING_INTERVAL_QUARTERLY";
    case PaymentBillingInterval.PAYMENT_BILLING_INTERVAL_YEARLY:
      return "PAYMENT_BILLING_INTERVAL_YEARLY";
    case PaymentBillingInterval.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum PaymentEventType {
  PAYMENT_EVENT_TYPE_UNSPECIFIED = 0,
  PAYMENT_EVENT_TYPE_CHECKOUT_COMPLETED = 1,
  PAYMENT_EVENT_TYPE_PAYMENT_SUCCEEDED = 2,
  PAYMENT_EVENT_TYPE_PAYMENT_FAILED = 3,
  PAYMENT_EVENT_TYPE_SUBSCRIPTION_CREATED = 4,
  PAYMENT_EVENT_TYPE_SUBSCRIPTION_RENEWED = 5,
  PAYMENT_EVENT_TYPE_SUBSCRIPTION_CANCELED = 6,
  PAYMENT_EVENT_TYPE_REFUND_CREATED = 7,
  PAYMENT_EVENT_TYPE_CHARGE_DISPUTED = 8,
  UNRECOGNIZED = -1,
}

export function paymentEventTypeFromJSON(object: any): PaymentEventType {
  switch (object) {
    case 0:
    case "PAYMENT_EVENT_TYPE_UNSPECIFIED":
      return PaymentEventType.PAYMENT_EVENT_TYPE_UNSPECIFIED;
    case 1:
    case "PAYMENT_EVENT_TYPE_CHECKOUT_COMPLETED":
      return PaymentEventType.PAYMENT_EVENT_TYPE_CHECKOUT_COMPLETED;
    case 2:
    case "PAYMENT_EVENT_TYPE_PAYMENT_SUCCEEDED":
      return PaymentEventType.PAYMENT_EVENT_TYPE_PAYMENT_SUCCEEDED;
    case 3:
    case "PAYMENT_EVENT_TYPE_PAYMENT_FAILED":
      return PaymentEventType.PAYMENT_EVENT_TYPE_PAYMENT_FAILED;
    case 4:
    case "PAYMENT_EVENT_TYPE_SUBSCRIPTION_CREATED":
      return PaymentEventType.PAYMENT_EVENT_TYPE_SUBSCRIPTION_CREATED;
    case 5:
    case "PAYMENT_EVENT_TYPE_SUBSCRIPTION_RENEWED":
      return PaymentEventType.PAYMENT_EVENT_TYPE_SUBSCRIPTION_RENEWED;
    case 6:
    case "PAYMENT_EVENT_TYPE_SUBSCRIPTION_CANCELED":
      return PaymentEventType.PAYMENT_EVENT_TYPE_SUBSCRIPTION_CANCELED;
    case 7:
    case "PAYMENT_EVENT_TYPE_REFUND_CREATED":
      return PaymentEventType.PAYMENT_EVENT_TYPE_REFUND_CREATED;
    case 8:
    case "PAYMENT_EVENT_TYPE_CHARGE_DISPUTED":
      return PaymentEventType.PAYMENT_EVENT_TYPE_CHARGE_DISPUTED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PaymentEventType.UNRECOGNIZED;
  }
}

export function paymentEventTypeToJSON(object: PaymentEventType): string {
  switch (object) {
    case PaymentEventType.PAYMENT_EVENT_TYPE_UNSPECIFIED:
      return "PAYMENT_EVENT_TYPE_UNSPECIFIED";
    case PaymentEventType.PAYMENT_EVENT_TYPE_CHECKOUT_COMPLETED:
      return "PAYMENT_EVENT_TYPE_CHECKOUT_COMPLETED";
    case PaymentEventType.PAYMENT_EVENT_TYPE_PAYMENT_SUCCEEDED:
      return "PAYMENT_EVENT_TYPE_PAYMENT_SUCCEEDED";
    case PaymentEventType.PAYMENT_EVENT_TYPE_PAYMENT_FAILED:
      return "PAYMENT_EVENT_TYPE_PAYMENT_FAILED";
    case PaymentEventType.PAYMENT_EVENT_TYPE_SUBSCRIPTION_CREATED:
      return "PAYMENT_EVENT_TYPE_SUBSCRIPTION_CREATED";
    case PaymentEventType.PAYMENT_EVENT_TYPE_SUBSCRIPTION_RENEWED:
      return "PAYMENT_EVENT_TYPE_SUBSCRIPTION_RENEWED";
    case PaymentEventType.PAYMENT_EVENT_TYPE_SUBSCRIPTION_CANCELED:
      return "PAYMENT_EVENT_TYPE_SUBSCRIPTION_CANCELED";
    case PaymentEventType.PAYMENT_EVENT_TYPE_REFUND_CREATED:
      return "PAYMENT_EVENT_TYPE_REFUND_CREATED";
    case PaymentEventType.PAYMENT_EVENT_TYPE_CHARGE_DISPUTED:
      return "PAYMENT_EVENT_TYPE_CHARGE_DISPUTED";
    case PaymentEventType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface CheckoutLineItem {
  name: string;
  description: string;
  amount_minor: number;
  quantity: number;
  external_product_id: string;
}

export interface CreateCheckoutRequest {
  business_id: string;
  subject_id: string;
  provider: PaymentProviderKind;
  customer_email: string;
  currency: string;
  line_items: CheckoutLineItem[];
  billing_interval: PaymentBillingInterval;
  success_url: string;
  cancel_url: string;
  metadata: { [key: string]: string };
  idempotency_key: string;
}

export interface CreateCheckoutRequest_MetadataEntry {
  key: string;
  value: string;
}

export interface CreateCheckoutResponse {
  order_id: string;
  provider_session_id: string;
  checkout_url: string;
  provider: PaymentProviderKind;
}

export interface GetPaymentOrderRequest {
  order_id: string;
}

export interface PaymentOrderResponse {
  id: string;
  business_id: string;
  subject_id: string;
  provider: PaymentProviderKind;
  provider_session_id: string;
  status: PaymentOrderStatus;
  currency: string;
  total_amount_minor: number;
  billing_interval: string;
  metadata: { [key: string]: any } | undefined;
  created_at: string;
  updated_at: string;
}

export interface ListPaymentOrdersRequest {
  business_id: string;
  subject_id: string;
  status: PaymentOrderStatus;
  page_size: number;
  page_token: string;
}

export interface ListPaymentOrdersResponse {
  orders: PaymentOrderResponse[];
  next_page_token: string;
}

export interface RefundPaymentRequest {
  order_id: string;
  amount_minor: number;
  reason: string;
  idempotency_key: string;
}

export interface RefundPaymentResponse {
  refund_id: string;
  provider_refund_id: string;
  amount_minor: number;
  status: string;
}

export interface PaymentWebhookRequest {
  provider: PaymentProviderKind;
  raw_body: Uint8Array;
  signature: string;
}

export interface PaymentWebhookResponse {
  accepted: boolean;
  event_type: string;
  provider_event_id: string;
  order_id: string;
}

export interface ListPaymentProvidersRequest {
}

export interface ListPaymentProvidersResponse {
  providers: string[];
}

function createBaseCheckoutLineItem(): CheckoutLineItem {
  return { name: "", description: "", amount_minor: 0, quantity: 0, external_product_id: "" };
}

export const CheckoutLineItem: MessageFns<CheckoutLineItem> = {
  encode(message: CheckoutLineItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    if (message.amount_minor !== 0) {
      writer.uint32(24).int64(message.amount_minor);
    }
    if (message.quantity !== 0) {
      writer.uint32(32).uint32(message.quantity);
    }
    if (message.external_product_id !== "") {
      writer.uint32(42).string(message.external_product_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CheckoutLineItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCheckoutLineItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.amount_minor = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.quantity = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.external_product_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CheckoutLineItem {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      amount_minor: isSet(object.amount_minor) ? globalThis.Number(object.amount_minor) : 0,
      quantity: isSet(object.quantity) ? globalThis.Number(object.quantity) : 0,
      external_product_id: isSet(object.external_product_id) ? globalThis.String(object.external_product_id) : "",
    };
  },

  toJSON(message: CheckoutLineItem): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.amount_minor !== 0) {
      obj.amount_minor = Math.round(message.amount_minor);
    }
    if (message.quantity !== 0) {
      obj.quantity = Math.round(message.quantity);
    }
    if (message.external_product_id !== "") {
      obj.external_product_id = message.external_product_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CheckoutLineItem>, I>>(base?: I): CheckoutLineItem {
    return CheckoutLineItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CheckoutLineItem>, I>>(object: I): CheckoutLineItem {
    const message = createBaseCheckoutLineItem();
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.amount_minor = object.amount_minor ?? 0;
    message.quantity = object.quantity ?? 0;
    message.external_product_id = object.external_product_id ?? "";
    return message;
  },
};

function createBaseCreateCheckoutRequest(): CreateCheckoutRequest {
  return {
    business_id: "",
    subject_id: "",
    provider: 0,
    customer_email: "",
    currency: "",
    line_items: [],
    billing_interval: 0,
    success_url: "",
    cancel_url: "",
    metadata: {},
    idempotency_key: "",
  };
}

export const CreateCheckoutRequest: MessageFns<CreateCheckoutRequest> = {
  encode(message: CreateCheckoutRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.business_id !== "") {
      writer.uint32(10).string(message.business_id);
    }
    if (message.subject_id !== "") {
      writer.uint32(18).string(message.subject_id);
    }
    if (message.provider !== 0) {
      writer.uint32(24).int32(message.provider);
    }
    if (message.customer_email !== "") {
      writer.uint32(34).string(message.customer_email);
    }
    if (message.currency !== "") {
      writer.uint32(42).string(message.currency);
    }
    for (const v of message.line_items) {
      CheckoutLineItem.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.billing_interval !== 0) {
      writer.uint32(56).int32(message.billing_interval);
    }
    if (message.success_url !== "") {
      writer.uint32(66).string(message.success_url);
    }
    if (message.cancel_url !== "") {
      writer.uint32(74).string(message.cancel_url);
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      CreateCheckoutRequest_MetadataEntry.encode({ key: key as any, value }, writer.uint32(82).fork()).join();
    });
    if (message.idempotency_key !== "") {
      writer.uint32(90).string(message.idempotency_key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateCheckoutRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateCheckoutRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.business_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.subject_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.provider = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.customer_email = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.line_items.push(CheckoutLineItem.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.billing_interval = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.success_url = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.cancel_url = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          const entry10 = CreateCheckoutRequest_MetadataEntry.decode(reader, reader.uint32());
          if (entry10.value !== undefined) {
            message.metadata[entry10.key] = entry10.value;
          }
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.idempotency_key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateCheckoutRequest {
    return {
      business_id: isSet(object.business_id) ? globalThis.String(object.business_id) : "",
      subject_id: isSet(object.subject_id) ? globalThis.String(object.subject_id) : "",
      provider: isSet(object.provider) ? paymentProviderKindFromJSON(object.provider) : 0,
      customer_email: isSet(object.customer_email) ? globalThis.String(object.customer_email) : "",
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      line_items: globalThis.Array.isArray(object?.line_items)
        ? object.line_items.map((e: any) => CheckoutLineItem.fromJSON(e))
        : [],
      billing_interval: isSet(object.billing_interval) ? paymentBillingIntervalFromJSON(object.billing_interval) : 0,
      success_url: isSet(object.success_url) ? globalThis.String(object.success_url) : "",
      cancel_url: isSet(object.cancel_url) ? globalThis.String(object.cancel_url) : "",
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      idempotency_key: isSet(object.idempotency_key) ? globalThis.String(object.idempotency_key) : "",
    };
  },

  toJSON(message: CreateCheckoutRequest): unknown {
    const obj: any = {};
    if (message.business_id !== "") {
      obj.business_id = message.business_id;
    }
    if (message.subject_id !== "") {
      obj.subject_id = message.subject_id;
    }
    if (message.provider !== 0) {
      obj.provider = paymentProviderKindToJSON(message.provider);
    }
    if (message.customer_email !== "") {
      obj.customer_email = message.customer_email;
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.line_items?.length) {
      obj.line_items = message.line_items.map((e) => CheckoutLineItem.toJSON(e));
    }
    if (message.billing_interval !== 0) {
      obj.billing_interval = paymentBillingIntervalToJSON(message.billing_interval);
    }
    if (message.success_url !== "") {
      obj.success_url = message.success_url;
    }
    if (message.cancel_url !== "") {
      obj.cancel_url = message.cancel_url;
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    if (message.idempotency_key !== "") {
      obj.idempotency_key = message.idempotency_key;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateCheckoutRequest>, I>>(base?: I): CreateCheckoutRequest {
    return CreateCheckoutRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateCheckoutRequest>, I>>(object: I): CreateCheckoutRequest {
    const message = createBaseCreateCheckoutRequest();
    message.business_id = object.business_id ?? "";
    message.subject_id = object.subject_id ?? "";
    message.provider = object.provider ?? 0;
    message.customer_email = object.customer_email ?? "";
    message.currency = object.currency ?? "";
    message.line_items = object.line_items?.map((e) => CheckoutLineItem.fromPartial(e)) || [];
    message.billing_interval = object.billing_interval ?? 0;
    message.success_url = object.success_url ?? "";
    message.cancel_url = object.cancel_url ?? "";
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.idempotency_key = object.idempotency_key ?? "";
    return message;
  },
};

function createBaseCreateCheckoutRequest_MetadataEntry(): CreateCheckoutRequest_MetadataEntry {
  return { key: "", value: "" };
}

export const CreateCheckoutRequest_MetadataEntry: MessageFns<CreateCheckoutRequest_MetadataEntry> = {
  encode(message: CreateCheckoutRequest_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateCheckoutRequest_MetadataEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateCheckoutRequest_MetadataEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateCheckoutRequest_MetadataEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: CreateCheckoutRequest_MetadataEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateCheckoutRequest_MetadataEntry>, I>>(
    base?: I,
  ): CreateCheckoutRequest_MetadataEntry {
    return CreateCheckoutRequest_MetadataEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateCheckoutRequest_MetadataEntry>, I>>(
    object: I,
  ): CreateCheckoutRequest_MetadataEntry {
    const message = createBaseCreateCheckoutRequest_MetadataEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseCreateCheckoutResponse(): CreateCheckoutResponse {
  return { order_id: "", provider_session_id: "", checkout_url: "", provider: 0 };
}

export const CreateCheckoutResponse: MessageFns<CreateCheckoutResponse> = {
  encode(message: CreateCheckoutResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.order_id !== "") {
      writer.uint32(10).string(message.order_id);
    }
    if (message.provider_session_id !== "") {
      writer.uint32(18).string(message.provider_session_id);
    }
    if (message.checkout_url !== "") {
      writer.uint32(26).string(message.checkout_url);
    }
    if (message.provider !== 0) {
      writer.uint32(32).int32(message.provider);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateCheckoutResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateCheckoutResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.order_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.provider_session_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.checkout_url = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.provider = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateCheckoutResponse {
    return {
      order_id: isSet(object.order_id) ? globalThis.String(object.order_id) : "",
      provider_session_id: isSet(object.provider_session_id) ? globalThis.String(object.provider_session_id) : "",
      checkout_url: isSet(object.checkout_url) ? globalThis.String(object.checkout_url) : "",
      provider: isSet(object.provider) ? paymentProviderKindFromJSON(object.provider) : 0,
    };
  },

  toJSON(message: CreateCheckoutResponse): unknown {
    const obj: any = {};
    if (message.order_id !== "") {
      obj.order_id = message.order_id;
    }
    if (message.provider_session_id !== "") {
      obj.provider_session_id = message.provider_session_id;
    }
    if (message.checkout_url !== "") {
      obj.checkout_url = message.checkout_url;
    }
    if (message.provider !== 0) {
      obj.provider = paymentProviderKindToJSON(message.provider);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateCheckoutResponse>, I>>(base?: I): CreateCheckoutResponse {
    return CreateCheckoutResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateCheckoutResponse>, I>>(object: I): CreateCheckoutResponse {
    const message = createBaseCreateCheckoutResponse();
    message.order_id = object.order_id ?? "";
    message.provider_session_id = object.provider_session_id ?? "";
    message.checkout_url = object.checkout_url ?? "";
    message.provider = object.provider ?? 0;
    return message;
  },
};

function createBaseGetPaymentOrderRequest(): GetPaymentOrderRequest {
  return { order_id: "" };
}

export const GetPaymentOrderRequest: MessageFns<GetPaymentOrderRequest> = {
  encode(message: GetPaymentOrderRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.order_id !== "") {
      writer.uint32(10).string(message.order_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPaymentOrderRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPaymentOrderRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.order_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPaymentOrderRequest {
    return { order_id: isSet(object.order_id) ? globalThis.String(object.order_id) : "" };
  },

  toJSON(message: GetPaymentOrderRequest): unknown {
    const obj: any = {};
    if (message.order_id !== "") {
      obj.order_id = message.order_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPaymentOrderRequest>, I>>(base?: I): GetPaymentOrderRequest {
    return GetPaymentOrderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPaymentOrderRequest>, I>>(object: I): GetPaymentOrderRequest {
    const message = createBaseGetPaymentOrderRequest();
    message.order_id = object.order_id ?? "";
    return message;
  },
};

function createBasePaymentOrderResponse(): PaymentOrderResponse {
  return {
    id: "",
    business_id: "",
    subject_id: "",
    provider: 0,
    provider_session_id: "",
    status: 0,
    currency: "",
    total_amount_minor: 0,
    billing_interval: "",
    metadata: undefined,
    created_at: "",
    updated_at: "",
  };
}

export const PaymentOrderResponse: MessageFns<PaymentOrderResponse> = {
  encode(message: PaymentOrderResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.business_id !== "") {
      writer.uint32(18).string(message.business_id);
    }
    if (message.subject_id !== "") {
      writer.uint32(26).string(message.subject_id);
    }
    if (message.provider !== 0) {
      writer.uint32(32).int32(message.provider);
    }
    if (message.provider_session_id !== "") {
      writer.uint32(42).string(message.provider_session_id);
    }
    if (message.status !== 0) {
      writer.uint32(48).int32(message.status);
    }
    if (message.currency !== "") {
      writer.uint32(58).string(message.currency);
    }
    if (message.total_amount_minor !== 0) {
      writer.uint32(64).int64(message.total_amount_minor);
    }
    if (message.billing_interval !== "") {
      writer.uint32(74).string(message.billing_interval);
    }
    if (message.metadata !== undefined) {
      Struct.encode(Struct.wrap(message.metadata), writer.uint32(82).fork()).join();
    }
    if (message.created_at !== "") {
      writer.uint32(90).string(message.created_at);
    }
    if (message.updated_at !== "") {
      writer.uint32(98).string(message.updated_at);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PaymentOrderResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePaymentOrderResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.business_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.subject_id = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.provider = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.provider_session_id = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.total_amount_minor = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.billing_interval = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.metadata = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.created_at = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.updated_at = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PaymentOrderResponse {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      business_id: isSet(object.business_id) ? globalThis.String(object.business_id) : "",
      subject_id: isSet(object.subject_id) ? globalThis.String(object.subject_id) : "",
      provider: isSet(object.provider) ? paymentProviderKindFromJSON(object.provider) : 0,
      provider_session_id: isSet(object.provider_session_id) ? globalThis.String(object.provider_session_id) : "",
      status: isSet(object.status) ? paymentOrderStatusFromJSON(object.status) : 0,
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      total_amount_minor: isSet(object.total_amount_minor) ? globalThis.Number(object.total_amount_minor) : 0,
      billing_interval: isSet(object.billing_interval) ? globalThis.String(object.billing_interval) : "",
      metadata: isObject(object.metadata) ? object.metadata : undefined,
      created_at: isSet(object.created_at) ? globalThis.String(object.created_at) : "",
      updated_at: isSet(object.updated_at) ? globalThis.String(object.updated_at) : "",
    };
  },

  toJSON(message: PaymentOrderResponse): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.business_id !== "") {
      obj.business_id = message.business_id;
    }
    if (message.subject_id !== "") {
      obj.subject_id = message.subject_id;
    }
    if (message.provider !== 0) {
      obj.provider = paymentProviderKindToJSON(message.provider);
    }
    if (message.provider_session_id !== "") {
      obj.provider_session_id = message.provider_session_id;
    }
    if (message.status !== 0) {
      obj.status = paymentOrderStatusToJSON(message.status);
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.total_amount_minor !== 0) {
      obj.total_amount_minor = Math.round(message.total_amount_minor);
    }
    if (message.billing_interval !== "") {
      obj.billing_interval = message.billing_interval;
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    if (message.created_at !== "") {
      obj.created_at = message.created_at;
    }
    if (message.updated_at !== "") {
      obj.updated_at = message.updated_at;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PaymentOrderResponse>, I>>(base?: I): PaymentOrderResponse {
    return PaymentOrderResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PaymentOrderResponse>, I>>(object: I): PaymentOrderResponse {
    const message = createBasePaymentOrderResponse();
    message.id = object.id ?? "";
    message.business_id = object.business_id ?? "";
    message.subject_id = object.subject_id ?? "";
    message.provider = object.provider ?? 0;
    message.provider_session_id = object.provider_session_id ?? "";
    message.status = object.status ?? 0;
    message.currency = object.currency ?? "";
    message.total_amount_minor = object.total_amount_minor ?? 0;
    message.billing_interval = object.billing_interval ?? "";
    message.metadata = object.metadata ?? undefined;
    message.created_at = object.created_at ?? "";
    message.updated_at = object.updated_at ?? "";
    return message;
  },
};

function createBaseListPaymentOrdersRequest(): ListPaymentOrdersRequest {
  return { business_id: "", subject_id: "", status: 0, page_size: 0, page_token: "" };
}

export const ListPaymentOrdersRequest: MessageFns<ListPaymentOrdersRequest> = {
  encode(message: ListPaymentOrdersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.business_id !== "") {
      writer.uint32(10).string(message.business_id);
    }
    if (message.subject_id !== "") {
      writer.uint32(18).string(message.subject_id);
    }
    if (message.status !== 0) {
      writer.uint32(24).int32(message.status);
    }
    if (message.page_size !== 0) {
      writer.uint32(32).uint32(message.page_size);
    }
    if (message.page_token !== "") {
      writer.uint32(42).string(message.page_token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPaymentOrdersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPaymentOrdersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.business_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.subject_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.page_size = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.page_token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListPaymentOrdersRequest {
    return {
      business_id: isSet(object.business_id) ? globalThis.String(object.business_id) : "",
      subject_id: isSet(object.subject_id) ? globalThis.String(object.subject_id) : "",
      status: isSet(object.status) ? paymentOrderStatusFromJSON(object.status) : 0,
      page_size: isSet(object.page_size) ? globalThis.Number(object.page_size) : 0,
      page_token: isSet(object.page_token) ? globalThis.String(object.page_token) : "",
    };
  },

  toJSON(message: ListPaymentOrdersRequest): unknown {
    const obj: any = {};
    if (message.business_id !== "") {
      obj.business_id = message.business_id;
    }
    if (message.subject_id !== "") {
      obj.subject_id = message.subject_id;
    }
    if (message.status !== 0) {
      obj.status = paymentOrderStatusToJSON(message.status);
    }
    if (message.page_size !== 0) {
      obj.page_size = Math.round(message.page_size);
    }
    if (message.page_token !== "") {
      obj.page_token = message.page_token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListPaymentOrdersRequest>, I>>(base?: I): ListPaymentOrdersRequest {
    return ListPaymentOrdersRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListPaymentOrdersRequest>, I>>(object: I): ListPaymentOrdersRequest {
    const message = createBaseListPaymentOrdersRequest();
    message.business_id = object.business_id ?? "";
    message.subject_id = object.subject_id ?? "";
    message.status = object.status ?? 0;
    message.page_size = object.page_size ?? 0;
    message.page_token = object.page_token ?? "";
    return message;
  },
};

function createBaseListPaymentOrdersResponse(): ListPaymentOrdersResponse {
  return { orders: [], next_page_token: "" };
}

export const ListPaymentOrdersResponse: MessageFns<ListPaymentOrdersResponse> = {
  encode(message: ListPaymentOrdersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.orders) {
      PaymentOrderResponse.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.next_page_token !== "") {
      writer.uint32(18).string(message.next_page_token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPaymentOrdersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPaymentOrdersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orders.push(PaymentOrderResponse.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.next_page_token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListPaymentOrdersResponse {
    return {
      orders: globalThis.Array.isArray(object?.orders)
        ? object.orders.map((e: any) => PaymentOrderResponse.fromJSON(e))
        : [],
      next_page_token: isSet(object.next_page_token) ? globalThis.String(object.next_page_token) : "",
    };
  },

  toJSON(message: ListPaymentOrdersResponse): unknown {
    const obj: any = {};
    if (message.orders?.length) {
      obj.orders = message.orders.map((e) => PaymentOrderResponse.toJSON(e));
    }
    if (message.next_page_token !== "") {
      obj.next_page_token = message.next_page_token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListPaymentOrdersResponse>, I>>(base?: I): ListPaymentOrdersResponse {
    return ListPaymentOrdersResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListPaymentOrdersResponse>, I>>(object: I): ListPaymentOrdersResponse {
    const message = createBaseListPaymentOrdersResponse();
    message.orders = object.orders?.map((e) => PaymentOrderResponse.fromPartial(e)) || [];
    message.next_page_token = object.next_page_token ?? "";
    return message;
  },
};

function createBaseRefundPaymentRequest(): RefundPaymentRequest {
  return { order_id: "", amount_minor: 0, reason: "", idempotency_key: "" };
}

export const RefundPaymentRequest: MessageFns<RefundPaymentRequest> = {
  encode(message: RefundPaymentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.order_id !== "") {
      writer.uint32(10).string(message.order_id);
    }
    if (message.amount_minor !== 0) {
      writer.uint32(16).int64(message.amount_minor);
    }
    if (message.reason !== "") {
      writer.uint32(26).string(message.reason);
    }
    if (message.idempotency_key !== "") {
      writer.uint32(34).string(message.idempotency_key);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefundPaymentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefundPaymentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.order_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.amount_minor = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.idempotency_key = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RefundPaymentRequest {
    return {
      order_id: isSet(object.order_id) ? globalThis.String(object.order_id) : "",
      amount_minor: isSet(object.amount_minor) ? globalThis.Number(object.amount_minor) : 0,
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
      idempotency_key: isSet(object.idempotency_key) ? globalThis.String(object.idempotency_key) : "",
    };
  },

  toJSON(message: RefundPaymentRequest): unknown {
    const obj: any = {};
    if (message.order_id !== "") {
      obj.order_id = message.order_id;
    }
    if (message.amount_minor !== 0) {
      obj.amount_minor = Math.round(message.amount_minor);
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    if (message.idempotency_key !== "") {
      obj.idempotency_key = message.idempotency_key;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RefundPaymentRequest>, I>>(base?: I): RefundPaymentRequest {
    return RefundPaymentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefundPaymentRequest>, I>>(object: I): RefundPaymentRequest {
    const message = createBaseRefundPaymentRequest();
    message.order_id = object.order_id ?? "";
    message.amount_minor = object.amount_minor ?? 0;
    message.reason = object.reason ?? "";
    message.idempotency_key = object.idempotency_key ?? "";
    return message;
  },
};

function createBaseRefundPaymentResponse(): RefundPaymentResponse {
  return { refund_id: "", provider_refund_id: "", amount_minor: 0, status: "" };
}

export const RefundPaymentResponse: MessageFns<RefundPaymentResponse> = {
  encode(message: RefundPaymentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.refund_id !== "") {
      writer.uint32(10).string(message.refund_id);
    }
    if (message.provider_refund_id !== "") {
      writer.uint32(18).string(message.provider_refund_id);
    }
    if (message.amount_minor !== 0) {
      writer.uint32(24).int64(message.amount_minor);
    }
    if (message.status !== "") {
      writer.uint32(34).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RefundPaymentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRefundPaymentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.refund_id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.provider_refund_id = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.amount_minor = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RefundPaymentResponse {
    return {
      refund_id: isSet(object.refund_id) ? globalThis.String(object.refund_id) : "",
      provider_refund_id: isSet(object.provider_refund_id) ? globalThis.String(object.provider_refund_id) : "",
      amount_minor: isSet(object.amount_minor) ? globalThis.Number(object.amount_minor) : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: RefundPaymentResponse): unknown {
    const obj: any = {};
    if (message.refund_id !== "") {
      obj.refund_id = message.refund_id;
    }
    if (message.provider_refund_id !== "") {
      obj.provider_refund_id = message.provider_refund_id;
    }
    if (message.amount_minor !== 0) {
      obj.amount_minor = Math.round(message.amount_minor);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RefundPaymentResponse>, I>>(base?: I): RefundPaymentResponse {
    return RefundPaymentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RefundPaymentResponse>, I>>(object: I): RefundPaymentResponse {
    const message = createBaseRefundPaymentResponse();
    message.refund_id = object.refund_id ?? "";
    message.provider_refund_id = object.provider_refund_id ?? "";
    message.amount_minor = object.amount_minor ?? 0;
    message.status = object.status ?? "";
    return message;
  },
};

function createBasePaymentWebhookRequest(): PaymentWebhookRequest {
  return { provider: 0, raw_body: new Uint8Array(0), signature: "" };
}

export const PaymentWebhookRequest: MessageFns<PaymentWebhookRequest> = {
  encode(message: PaymentWebhookRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.provider !== 0) {
      writer.uint32(8).int32(message.provider);
    }
    if (message.raw_body.length !== 0) {
      writer.uint32(18).bytes(message.raw_body);
    }
    if (message.signature !== "") {
      writer.uint32(26).string(message.signature);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PaymentWebhookRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePaymentWebhookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.provider = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.raw_body = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.signature = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PaymentWebhookRequest {
    return {
      provider: isSet(object.provider) ? paymentProviderKindFromJSON(object.provider) : 0,
      raw_body: isSet(object.raw_body) ? bytesFromBase64(object.raw_body) : new Uint8Array(0),
      signature: isSet(object.signature) ? globalThis.String(object.signature) : "",
    };
  },

  toJSON(message: PaymentWebhookRequest): unknown {
    const obj: any = {};
    if (message.provider !== 0) {
      obj.provider = paymentProviderKindToJSON(message.provider);
    }
    if (message.raw_body.length !== 0) {
      obj.raw_body = base64FromBytes(message.raw_body);
    }
    if (message.signature !== "") {
      obj.signature = message.signature;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PaymentWebhookRequest>, I>>(base?: I): PaymentWebhookRequest {
    return PaymentWebhookRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PaymentWebhookRequest>, I>>(object: I): PaymentWebhookRequest {
    const message = createBasePaymentWebhookRequest();
    message.provider = object.provider ?? 0;
    message.raw_body = object.raw_body ?? new Uint8Array(0);
    message.signature = object.signature ?? "";
    return message;
  },
};

function createBasePaymentWebhookResponse(): PaymentWebhookResponse {
  return { accepted: false, event_type: "", provider_event_id: "", order_id: "" };
}

export const PaymentWebhookResponse: MessageFns<PaymentWebhookResponse> = {
  encode(message: PaymentWebhookResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accepted !== false) {
      writer.uint32(8).bool(message.accepted);
    }
    if (message.event_type !== "") {
      writer.uint32(18).string(message.event_type);
    }
    if (message.provider_event_id !== "") {
      writer.uint32(26).string(message.provider_event_id);
    }
    if (message.order_id !== "") {
      writer.uint32(34).string(message.order_id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PaymentWebhookResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePaymentWebhookResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.accepted = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.event_type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.provider_event_id = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.order_id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PaymentWebhookResponse {
    return {
      accepted: isSet(object.accepted) ? globalThis.Boolean(object.accepted) : false,
      event_type: isSet(object.event_type) ? globalThis.String(object.event_type) : "",
      provider_event_id: isSet(object.provider_event_id) ? globalThis.String(object.provider_event_id) : "",
      order_id: isSet(object.order_id) ? globalThis.String(object.order_id) : "",
    };
  },

  toJSON(message: PaymentWebhookResponse): unknown {
    const obj: any = {};
    if (message.accepted !== false) {
      obj.accepted = message.accepted;
    }
    if (message.event_type !== "") {
      obj.event_type = message.event_type;
    }
    if (message.provider_event_id !== "") {
      obj.provider_event_id = message.provider_event_id;
    }
    if (message.order_id !== "") {
      obj.order_id = message.order_id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PaymentWebhookResponse>, I>>(base?: I): PaymentWebhookResponse {
    return PaymentWebhookResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PaymentWebhookResponse>, I>>(object: I): PaymentWebhookResponse {
    const message = createBasePaymentWebhookResponse();
    message.accepted = object.accepted ?? false;
    message.event_type = object.event_type ?? "";
    message.provider_event_id = object.provider_event_id ?? "";
    message.order_id = object.order_id ?? "";
    return message;
  },
};

function createBaseListPaymentProvidersRequest(): ListPaymentProvidersRequest {
  return {};
}

export const ListPaymentProvidersRequest: MessageFns<ListPaymentProvidersRequest> = {
  encode(_: ListPaymentProvidersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPaymentProvidersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPaymentProvidersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ListPaymentProvidersRequest {
    return {};
  },

  toJSON(_: ListPaymentProvidersRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ListPaymentProvidersRequest>, I>>(base?: I): ListPaymentProvidersRequest {
    return ListPaymentProvidersRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListPaymentProvidersRequest>, I>>(_: I): ListPaymentProvidersRequest {
    const message = createBaseListPaymentProvidersRequest();
    return message;
  },
};

function createBaseListPaymentProvidersResponse(): ListPaymentProvidersResponse {
  return { providers: [] };
}

export const ListPaymentProvidersResponse: MessageFns<ListPaymentProvidersResponse> = {
  encode(message: ListPaymentProvidersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.providers) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListPaymentProvidersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListPaymentProvidersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.providers.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListPaymentProvidersResponse {
    return {
      providers: globalThis.Array.isArray(object?.providers)
        ? object.providers.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: ListPaymentProvidersResponse): unknown {
    const obj: any = {};
    if (message.providers?.length) {
      obj.providers = message.providers;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListPaymentProvidersResponse>, I>>(base?: I): ListPaymentProvidersResponse {
    return ListPaymentProvidersResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListPaymentProvidersResponse>, I>>(object: I): ListPaymentProvidersResponse {
    const message = createBaseListPaymentProvidersResponse();
    message.providers = object.providers?.map((e) => e) || [];
    return message;
  },
};

export interface PaymentGatewayService {
  /** Create a checkout session on an external payment platform. */
  CreateCheckout(request: CreateCheckoutRequest): Promise<CreateCheckoutResponse>;
  /** Get a payment order by ID. */
  GetPaymentOrder(request: GetPaymentOrderRequest): Promise<PaymentOrderResponse>;
  /** List payment orders with optional filters. */
  ListPaymentOrders(request: ListPaymentOrdersRequest): Promise<ListPaymentOrdersResponse>;
  /** Refund a payment order (full or partial). */
  RefundPayment(request: RefundPaymentRequest): Promise<RefundPaymentResponse>;
  /** Receive and process webhook from a payment provider. */
  HandleWebhook(request: PaymentWebhookRequest): Promise<PaymentWebhookResponse>;
  /** List available payment providers. */
  ListPaymentProviders(request: ListPaymentProvidersRequest): Promise<ListPaymentProvidersResponse>;
}

export const PaymentGatewayServiceServiceName = "stew.api.v1.PaymentGatewayService";
export class PaymentGatewayServiceClientImpl implements PaymentGatewayService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || PaymentGatewayServiceServiceName;
    this.rpc = rpc;
    this.CreateCheckout = this.CreateCheckout.bind(this);
    this.GetPaymentOrder = this.GetPaymentOrder.bind(this);
    this.ListPaymentOrders = this.ListPaymentOrders.bind(this);
    this.RefundPayment = this.RefundPayment.bind(this);
    this.HandleWebhook = this.HandleWebhook.bind(this);
    this.ListPaymentProviders = this.ListPaymentProviders.bind(this);
  }
  CreateCheckout(request: CreateCheckoutRequest): Promise<CreateCheckoutResponse> {
    const data = CreateCheckoutRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateCheckout", data);
    return promise.then((data) => CreateCheckoutResponse.decode(new BinaryReader(data)));
  }

  GetPaymentOrder(request: GetPaymentOrderRequest): Promise<PaymentOrderResponse> {
    const data = GetPaymentOrderRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetPaymentOrder", data);
    return promise.then((data) => PaymentOrderResponse.decode(new BinaryReader(data)));
  }

  ListPaymentOrders(request: ListPaymentOrdersRequest): Promise<ListPaymentOrdersResponse> {
    const data = ListPaymentOrdersRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListPaymentOrders", data);
    return promise.then((data) => ListPaymentOrdersResponse.decode(new BinaryReader(data)));
  }

  RefundPayment(request: RefundPaymentRequest): Promise<RefundPaymentResponse> {
    const data = RefundPaymentRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "RefundPayment", data);
    return promise.then((data) => RefundPaymentResponse.decode(new BinaryReader(data)));
  }

  HandleWebhook(request: PaymentWebhookRequest): Promise<PaymentWebhookResponse> {
    const data = PaymentWebhookRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "HandleWebhook", data);
    return promise.then((data) => PaymentWebhookResponse.decode(new BinaryReader(data)));
  }

  ListPaymentProviders(request: ListPaymentProvidersRequest): Promise<ListPaymentProvidersResponse> {
    const data = ListPaymentProvidersRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListPaymentProviders", data);
    return promise.then((data) => ListPaymentProvidersResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
