// Code generated by protoc-gen-ts_client. DO NOT EDIT.
// source: user.proto
// Re-run `make ts` in the proto/ directory to regenerate this file.

import axios, { AxiosInstance, AxiosResponse } from 'axios';
import { APIResponse } from 'protobuf-typescript-client-gen';

// Import all required models
import { Empty } from './google/protobuf/empty';
import { UpdateUserRequest, UploadAvatarRequest, UploadAvatarResponse, User } from './user';


export interface ClientConfig {
  baseUrl: string;
  timeout?: number;
}

export interface EmptyRequest {}

type ResponseWrapper<T> = { data?: T } | T;

/**
 * Convert Uint8Array to Base64 string
 */
function uint8ArrayToBase64(bytes: Uint8Array): string {
  if (typeof window !== 'undefined' && window.btoa) {
    // Browser environment
    const binary = Array.from(bytes).map(b => String.fromCharCode(b)).join('');
    return window.btoa(binary);
  } else {
    // Node.js environment
    return Buffer.from(bytes).toString('base64');
  }
}

/**
 * Recursively convert all Uint8Array fields to Base64 strings in request object
 */
function preprocessRequest(obj: any): any {
  if (!obj || typeof obj !== 'object') {
    return obj;
  }

  if (obj instanceof Uint8Array) {
    return uint8ArrayToBase64(obj);
  }

  if (Array.isArray(obj)) {
    return obj.map(item => preprocessRequest(item));
  }

  const result: any = {};
  for (const [key, value] of Object.entries(obj)) {
    result[key] = preprocessRequest(value);
  }
  return result;
}

/**
 * Type guard to check if a value is an APIResponse structure
 */
function isAPIResponse(data: any): data is APIResponse {
  return (
    data !== null &&
    typeof data === 'object' &&
    typeof data.code === 'number' &&
    'data' in data &&
    'message' in data
  );
}

export class V1Client {
  private client: AxiosInstance;
  private baseUrl: string;
  private accessToken: string | null = null;
  private tokenExpiry: Date | null = null;

  constructor(config: ClientConfig) {
    this.baseUrl = config.baseUrl.replace(/\/$/, '');
    
    this.client = axios.create({
      baseURL: this.baseUrl,
      timeout: config.timeout || 30000,
      headers: {
        'Content-Type': 'application/json',
      },
      withCredentials: true, // 允许发送 Cookie
    });

    // Add request interceptor for authentication
    this.client.interceptors.request.use(async (config) => {
      // 处理 Session-based 认证
      this.ensureSessionCookie();
      
      // 处理 Bearer token 认证
      this.accessToken = this.getToken();
      if (this.accessToken) {
        config.headers.Authorization = `Bearer ${this.accessToken}`;
      }
      return config;
    });

    // Add response interceptor to handle authentication failures
    this.client.interceptors.response.use(
      (response) => response,
      (error) => {
        // Check for authentication errors (401 Unauthorized)
        if (error.response && error.response.status === 401) {
          this.clearAuthState();
        }
        return Promise.reject(error);
      }
    );
  }

  /**
   * 手动登出 - 清除所有认证状态
   * 公共方法，允许用户主动调用
   */
  public logout(): void {
    this.clearAuthState();
  }

  /**
   * 清除所有认证状态
   * 当认证失败时调用，清除 localStorage、sessionStorage 和所有 Cookie
   */
  private clearAuthState(): void {
    // 仅在浏览器环境中执行
    if (typeof window === 'undefined') {
      return;
    }

    try {
      // 清除 localStorage 中的认证相关信息
      if (typeof localStorage !== 'undefined') {
        localStorage.removeItem('session_id');
        localStorage.removeItem('token');
        localStorage.removeItem('access_token');
        localStorage.removeItem('refresh_token');
        console.debug('[Auth] Cleared localStorage auth data');
      }

      // 清除 sessionStorage 中的认证相关信息
      if (typeof sessionStorage !== 'undefined') {
        sessionStorage.removeItem('session_id');
        sessionStorage.removeItem('token');
        sessionStorage.removeItem('access_token');
        sessionStorage.removeItem('refresh_token');
        console.debug('[Auth] Cleared sessionStorage auth data');
      }

      // 清除所有 Cookie
      if (typeof document !== 'undefined' && document.cookie) {
        const cookies = document.cookie.split(';');
        for (let cookie of cookies) {
          const [name] = cookie.trim().split('=');
          if (name) {
            // 删除 Cookie（设置过期时间为过去）
            // 尝试多种路径和域组合以确保删除
            document.cookie = `${name}=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;`;
            document.cookie = `${name}=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/; domain=${window.location.hostname};`;
            
            // 如果域名有子域，尝试删除父域的 Cookie
            const hostnameParts = window.location.hostname.split('.');
            if (hostnameParts.length > 2) {
              const parentDomain = hostnameParts.slice(-2).join('.');
              document.cookie = `${name}=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/; domain=.${parentDomain};`;
            }
          }
        }
        console.debug('[Auth] Cleared all cookies');
      }

      // 清除当前实例的 token
      this.accessToken = null;
      this.tokenExpiry = null;

      console.warn('[Auth] Authentication failed - all auth state cleared');
    } catch (error) {
      console.error('[Auth] Failed to clear auth state:', error);
    }
  }

  /**
   * 确保 session_id Cookie 已设置
   * 从 localStorage 读取 session_id，如果存在则设置到 Cookie
   */
  private ensureSessionCookie(): void {
    // 仅在浏览器环境中执行
    if (typeof window === 'undefined' || typeof document === 'undefined') {
      return;
    }

    try {
      // 从 localStorage 读取 session_id
      const sessionId = localStorage.getItem('session_id');
      
      if (sessionId) {
        // 检查 Cookie 中是否已存在 session_id
        const cookies = document.cookie.split(';');
        const hasSessionCookie = cookies.some(cookie => {
          const [name] = cookie.trim().split('=');
          return name === 'session_id';
        });

        // 如果 Cookie 中没有 session_id，则设置它
        if (!hasSessionCookie) {
          // 设置 Cookie（路径为 /，SameSite=Lax 以支持跨页面导航）
          document.cookie = `session_id=${sessionId}; path=/; SameSite=Lax`;
          console.debug('[Auth] Set session_id cookie from localStorage');
        }
      }
    } catch (error) {
      console.warn('[Auth] Failed to sync session_id to cookie:', error);
    }
  }

  /**
   * 从 localStorage/Cookie 获取 session_id
   */
  private getSessionId(): string | null {
    // 检查浏览器环境
    if (typeof window !== 'undefined') {
      // 优先从 localStorage 获取
      if (typeof localStorage !== 'undefined') {
        const sessionId = localStorage.getItem('session_id');
        if (sessionId) {
          return sessionId;
        }
      }
      
      // 从 Cookie 获取作为后备
      if (typeof document !== 'undefined' && document.cookie) {
        const cookies = document.cookie.split(';');
        for (let cookie of cookies) {
          const [name, value] = cookie.trim().split('=');
          if (name === 'session_id') {
            return decodeURIComponent(value);
          }
        }
      }
    }
    
    return null;
  }

private getToken(): string | null {
  // Check if we're in a browser environment
  if (typeof window !== 'undefined') {
    // Browser environment - use localStorage, sessionStorage, and cookies
    
    // 从localStorage获取token
    if (typeof localStorage !== 'undefined') {
      const token = localStorage.getItem('token') || localStorage.getItem('access_token');
      if (token) {
        return token;
      }
    }
    
    // 从sessionStorage获取token
    if (typeof sessionStorage !== 'undefined') {
      const sessionToken = sessionStorage.getItem('token') || sessionStorage.getItem('access_token');
      if (sessionToken) {
        return sessionToken;
      }
    }
    
    // 从cookie获取token（如果使用cookie存储）
    if (typeof document !== 'undefined' && document.cookie) {
      const cookies = document.cookie.split(';');
      for (let cookie of cookies) {
        const [name, value] = cookie.trim().split('=');
        if (name === 'token' || name === 'access_token') {
          return decodeURIComponent(value);
        }
      }
    }
  } else if (typeof process !== 'undefined' && process.env) {
    // Node.js environment - try to get token from environment variables
    return process.env.ACCESS_TOKEN || process.env.TOKEN || null;
  }
  
  return null;
}

  private async getAuthHeaders(): Promise<Record<string, string>> {
    this.accessToken = this.getToken();
    return this.accessToken ? { Authorization: `Bearer ${this.accessToken}` } : {};
  }

  // UserService methods
  async get(
    request: Empty,
    headers?: Record<string, string>
  ): Promise<User> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/auth/user`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // GET/DELETE/HEAD/OPTIONS: pass params in config object
    const response: AxiosResponse<any> = await this.client.get(
      url,
      { 
        params: processedRequest,
        headers: requestHeaders 
      }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[UserService] Extracting user from nested structure:', userData.user);
          return User.fromJSON(userData.user);
        }

        console.log('[UserService] Using data directly as User:', userData);
        return User.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[UserService] Using response.data directly as User:', response.data);
      return User.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[UserService] Using response directly as User (non-wrapped):', response.data);
    return User.fromJSON(response.data);
  }
  async update(
    request: UpdateUserRequest,
    headers?: Record<string, string>
  ): Promise<User> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/auth/user`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // POST/PUT/PATCH: pass data as second parameter
    //     // v1.0.1

    const response: AxiosResponse<any> = await this.client.put(
      url,
      processedRequest,
      { headers: requestHeaders }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[UserService] Extracting user from nested structure:', userData.user);
          return User.fromJSON(userData.user);
        }

        console.log('[UserService] Using data directly as User:', userData);
        return User.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[UserService] Using response.data directly as User:', response.data);
      return User.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[UserService] Using response directly as User (non-wrapped):', response.data);
    return User.fromJSON(response.data);
  }
  async upload_avatar(
    request: UploadAvatarRequest,
    headers?: Record<string, string>
  ): Promise<UploadAvatarResponse> {
    // Extract and replace path parameters (supports nested fields like {service.service_name})
    let url = `/auth/user/avatar`;
    const pathParams = url.match(/{([^}]+)}/g);
    if (pathParams) {
      pathParams.forEach((param: string) => {
        const fieldPath = param.slice(1, -1); // Remove { and }
        const parts = fieldPath.split('.');
        let value: any = request;
        
        // Navigate nested fields
        for (const part of parts) {
          value = value?.[part];
        }
        
        if (value !== undefined && value !== null) {
          url = url.replace(param, encodeURIComponent(String(value)));
        }
      });
    }
    
    // Preprocess request to convert Uint8Array to Base64
    const processedRequest = preprocessRequest(request);
    
    const requestHeaders = { ...headers };
    
    
    // POST/PUT/PATCH: pass data as second parameter
    //     // v1.0.1

    const response: AxiosResponse<any> = await this.client.post(
      url,
      processedRequest,
      { headers: requestHeaders }
    );
    
    // Handle response format (APIResponse wrapper or direct response)
    if (isAPIResponse(response.data)) {
      // Check if wrapped in APIResponse format
      if (response.data.data !== undefined) {
        // API response format: { code: 2000, data: { user: {...}, session_id: "...", expires_at: ... }, message: "..." }
        const userData = response.data.data;

        // Check if data contains a nested 'user' object
        if (userData && typeof userData === 'object' && 'user' in userData) {
          console.log('[UserService] Extracting user from nested structure:', userData.user);
          return UploadAvatarResponse.fromJSON(userData.user);
        }

        console.log('[UserService] Using data directly as UploadAvatarResponse:', userData);
        return UploadAvatarResponse.fromJSON(userData);
      }
      // Direct response (APIResponse but without data field - shouldn't normally happen)
      console.log('[UserService] Using response.data directly as UploadAvatarResponse:', response.data);
      return UploadAvatarResponse.fromJSON(response.data);
    }
    // Not an APIResponse - treat as direct protobuf response
    console.log('[UserService] Using response directly as UploadAvatarResponse (non-wrapped):', response.data);
    return UploadAvatarResponse.fromJSON(response.data);
  }
}