// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.5
//   protoc               v3.21.12
// source: user.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Any } from "./google/protobuf/any";
import { Empty } from "./google/protobuf/empty";
import { FieldMask } from "./google/protobuf/field_mask";

export const protobufPackage = "stew.api.v1";

export enum Role {
  ADMIN = 0,
  UNRECOGNIZED = -1,
}

export function roleFromJSON(object: any): Role {
  switch (object) {
    case 0:
    case "ADMIN":
      return Role.ADMIN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Role.UNRECOGNIZED;
  }
}

export function roleToJSON(object: Role): string {
  switch (object) {
    case Role.ADMIN:
      return "ADMIN";
    case Role.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum USER_STATUS {
  ACTIVE = 0,
  INACTIVE = 1,
  LOCKED = 2,
  DELETED = 3,
  UNRECOGNIZED = -1,
}

export function uSER_STATUSFromJSON(object: any): USER_STATUS {
  switch (object) {
    case 0:
    case "ACTIVE":
      return USER_STATUS.ACTIVE;
    case 1:
    case "INACTIVE":
      return USER_STATUS.INACTIVE;
    case 2:
    case "LOCKED":
      return USER_STATUS.LOCKED;
    case 3:
    case "DELETED":
      return USER_STATUS.DELETED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return USER_STATUS.UNRECOGNIZED;
  }
}

export function uSER_STATUSToJSON(object: USER_STATUS): string {
  switch (object) {
    case USER_STATUS.ACTIVE:
      return "ACTIVE";
    case USER_STATUS.INACTIVE:
      return "INACTIVE";
    case USER_STATUS.LOCKED:
      return "LOCKED";
    case USER_STATUS.DELETED:
      return "DELETED";
    case USER_STATUS.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum UserSvrCode {
  USER_UNKNOWN = 0,
  USER_LOGIN_ERR = 4107,
  USER_TOKEN_EXPIRE_ERR = 4108,
  USER_DISABLED_ERR = 4119,
  /** USER_TOKEN_INVALIDATE_ERR - 非法的token */
  USER_TOKEN_INVALIDATE_ERR = 4109,
  USER_TOKEN_NOT_ACTIVTE_ERR = 4114,
  USER_AUTH_DECRYPT_ERR = 4110,
  USER_ACCOUNT_ERR = 4111,
  USER_PASSWORD_ERR = 4112,
  USER_NOT_FOUND_ERR = 4113,
  USER_AUTH_MISSING_ERR = 4115,
  USER_IDENTITY_MISSING_ERR = 4116,
  USER_APIKEY_NOT_MATCH_ERR = 4117,
  USER_USERNAME_DUPLICATE_ERR = 4118,
  UNRECOGNIZED = -1,
}

export function userSvrCodeFromJSON(object: any): UserSvrCode {
  switch (object) {
    case 0:
    case "USER_UNKNOWN":
      return UserSvrCode.USER_UNKNOWN;
    case 4107:
    case "USER_LOGIN_ERR":
      return UserSvrCode.USER_LOGIN_ERR;
    case 4108:
    case "USER_TOKEN_EXPIRE_ERR":
      return UserSvrCode.USER_TOKEN_EXPIRE_ERR;
    case 4119:
    case "USER_DISABLED_ERR":
      return UserSvrCode.USER_DISABLED_ERR;
    case 4109:
    case "USER_TOKEN_INVALIDATE_ERR":
      return UserSvrCode.USER_TOKEN_INVALIDATE_ERR;
    case 4114:
    case "USER_TOKEN_NOT_ACTIVTE_ERR":
      return UserSvrCode.USER_TOKEN_NOT_ACTIVTE_ERR;
    case 4110:
    case "USER_AUTH_DECRYPT_ERR":
      return UserSvrCode.USER_AUTH_DECRYPT_ERR;
    case 4111:
    case "USER_ACCOUNT_ERR":
      return UserSvrCode.USER_ACCOUNT_ERR;
    case 4112:
    case "USER_PASSWORD_ERR":
      return UserSvrCode.USER_PASSWORD_ERR;
    case 4113:
    case "USER_NOT_FOUND_ERR":
      return UserSvrCode.USER_NOT_FOUND_ERR;
    case 4115:
    case "USER_AUTH_MISSING_ERR":
      return UserSvrCode.USER_AUTH_MISSING_ERR;
    case 4116:
    case "USER_IDENTITY_MISSING_ERR":
      return UserSvrCode.USER_IDENTITY_MISSING_ERR;
    case 4117:
    case "USER_APIKEY_NOT_MATCH_ERR":
      return UserSvrCode.USER_APIKEY_NOT_MATCH_ERR;
    case 4118:
    case "USER_USERNAME_DUPLICATE_ERR":
      return UserSvrCode.USER_USERNAME_DUPLICATE_ERR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return UserSvrCode.UNRECOGNIZED;
  }
}

export function userSvrCodeToJSON(object: UserSvrCode): string {
  switch (object) {
    case UserSvrCode.USER_UNKNOWN:
      return "USER_UNKNOWN";
    case UserSvrCode.USER_LOGIN_ERR:
      return "USER_LOGIN_ERR";
    case UserSvrCode.USER_TOKEN_EXPIRE_ERR:
      return "USER_TOKEN_EXPIRE_ERR";
    case UserSvrCode.USER_DISABLED_ERR:
      return "USER_DISABLED_ERR";
    case UserSvrCode.USER_TOKEN_INVALIDATE_ERR:
      return "USER_TOKEN_INVALIDATE_ERR";
    case UserSvrCode.USER_TOKEN_NOT_ACTIVTE_ERR:
      return "USER_TOKEN_NOT_ACTIVTE_ERR";
    case UserSvrCode.USER_AUTH_DECRYPT_ERR:
      return "USER_AUTH_DECRYPT_ERR";
    case UserSvrCode.USER_ACCOUNT_ERR:
      return "USER_ACCOUNT_ERR";
    case UserSvrCode.USER_PASSWORD_ERR:
      return "USER_PASSWORD_ERR";
    case UserSvrCode.USER_NOT_FOUND_ERR:
      return "USER_NOT_FOUND_ERR";
    case UserSvrCode.USER_AUTH_MISSING_ERR:
      return "USER_AUTH_MISSING_ERR";
    case UserSvrCode.USER_IDENTITY_MISSING_ERR:
      return "USER_IDENTITY_MISSING_ERR";
    case UserSvrCode.USER_APIKEY_NOT_MATCH_ERR:
      return "USER_APIKEY_NOT_MATCH_ERR";
    case UserSvrCode.USER_USERNAME_DUPLICATE_ERR:
      return "USER_USERNAME_DUPLICATE_ERR";
    case UserSvrCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Address {
  formatted: string;
  street_address: string;
  locality: string;
  region: string;
  postal_code: string;
  country: string;
}

export interface User {
  /** @gotags: validate:"required" doc:"Subject - Identifier for the End-User at the Issuer" */
  sub: string;
  /** @gotags: validate:"required" doc:"End-User's full name in displayable form including all name parts, possibly including titles and suffixes" */
  name: string;
  /** @gotags: doc:"Given name(s) or first name(s) of the End-User" json:"given_name" */
  given_name: string;
  /** @gotags: doc:"Surname(s) or last name(s) of the End-User" json:"family_name" */
  family_name: string;
  /** @gotags: doc:"Middle name(s) of the End-User" json:"middle_name" */
  middle_name: string;
  /** @gotags: doc:"Casual name of the End-User that may or may not be the same as the given_name" json:"nickname" */
  nickname: string;
  /** @gotags: doc:"Shorthand name by which the End-User wishes to be referred to at the RP" json:"preferred_username" */
  preferred_username: string;
  /** @gotags: doc:"URL of the End-User's profile page" json:"profile" */
  profile: string;
  /** @gotags: doc:"URL of the End-User's profile picture" json:"picture" */
  picture: string;
  /** @gotags: doc:"URL of the End-User's Web page or blog" json:"website" */
  website: string;
  /** @gotags: doc:"End-User's preferred e-mail address" json:"email" */
  email: string;
  /** @gotags: doc:"True if the End-User's e-mail address has been verified; otherwise false" json:"email_verified" */
  email_verified: boolean;
  /** @gotags: doc:"End-User's gender. Values defined by this specification are female and male" */
  gender: string;
  /** @gotags: doc:"End-User's birthday, represented as an ISO 8601-1 YYYY-MM-DD format" json:"birthdate" */
  birthdate: string;
  /** @gotags: doc:"String from IANA Time Zone Database representing the End-User's time zone" json:"zoneinfo" */
  zoneinfo: string;
  /** @gotags: doc:"End-User's locale, represented as a BCP47 language tag" json:"locale" */
  locale: string;
  /** @gotags: doc:"End-User's preferred telephone number. E.164 format is recommended" json:"phone_number" */
  phone_number: string;
  /** @gotags: doc:"True if the End-User's phone number has been verified; otherwise false" json:"phone_number_verified" */
  phone_number_verified: boolean;
  /** @gotags: doc:"End-User's preferred postal address" json:"address" gorm:"type:json" */
  address: Address[];
  /** @gotags: doc:"Time the End-User's information was last updated" json:"updated_at" gorm:"type:bigint" */
  updated_at: number;
  /** @gotags: validate:"required" doc:"Unique identifier for the user" json:"id" primary:"primary_key" gorm:"column:id;type:varchar(36);primaryKey;comment:Unique identifier for the user" */
  id: string;
  /** @gotags: doc:"Owner of the user" json:"owner" gorm:"column:owner;type:varchar(36);index;comment:Owner of the user" */
  owner: string;
  /** @gotags: doc:"Type of the user" json:"type" gorm:"column:type;type:varchar(32);index;comment:Type of the user" */
  type: string;
  /** @gotags: validate:"required" doc:"Password of the user" json:"password" gorm:"column:password;type:varchar(128);comment:Password of the user" */
  password: string;
  /** @gotags: doc:"Salt for the password" json:"password_salt" gorm:"column:password_salt;type:varchar(64);comment:Salt for the password" */
  password_salt: string;
  /** @gotags: doc:"Type of the password" json:"password_type" gorm:"column:password_type;type:varchar(32);comment:Type of the password" */
  password_type: string;
  /** @gotags: doc:"Display name of the user" json:"display_name" gorm:"column:display_name;type:varchar(128);index;comment:Display name of the user" */
  display_name: string;
  /** @gotags: doc:"First name of the user" json:"first_name" gorm:"column:first_name;type:varchar(64);comment:First name of the user" */
  first_name: string;
  /** @gotags: doc:"Last name of the user" json:"last_name" gorm:"column:last_name;type:varchar(64);comment:Last name of the user" */
  last_name: string;
  /** @gotags: doc:"Avatar URL of the user" json:"avatar" gorm:"column:avatar;type:varchar(512);comment:Avatar URL of the user" */
  avatar: string;
  /** @gotags: doc:"Type of the avatar" json:"avatar_type" gorm:"column:avatar_type;type:varchar(32);comment:Type of the avatar" */
  avatar_type: string;
  /** @gotags: doc:"Permanent avatar URL of the user" json:"permanent_avatar" gorm:"column:permanent_avatar;type:varchar(512);comment:Permanent avatar URL of the user" */
  permanent_avatar: string;
  /** @gotags: doc:"Additional properties of the user" json:"properties" gorm:"column:properties;type:json;comment:Additional properties of the user" */
  properties: { [key: string]: Any };
}

export interface User_PropertiesEntry {
  key: string;
  value: Any | undefined;
}

export interface BasicAuth {
  uid: string;
  name: string;
  role: Role;
  audience: string;
  issuer: string;
  not_before: number;
  expiration: number;
  issued_at: number;
  is_keep_login: boolean;
  token: string;
}

export interface PostUserRequest {
  name: string;
  password: string;
  email: string;
  phone: string;
  role: Role;
  status: USER_STATUS;
  dept: string;
  owner: string;
  /** @gotags: doc:"account avatar" gorm:"type:varchar(512);comment:Users account avatar" */
  avatar: string;
  /** @gotags: validate:"required" */
  tenant_id: string;
  /** @gotags: gorm:"-" json:"-" */
  update_mask: string[] | undefined;
}

export interface GetUserRequest {
  uid: string;
}

export interface DeleteUserRequest {
  uid: string;
}

export interface DeleteUserResponse {
  uid: string;
}

export interface PatchUserRequest {
  uid: string;
  name: string;
  password: string;
  email: string;
  phone: string;
  role: Role;
  status: USER_STATUS;
  dept: string;
  owner: string;
  /** @gotags: doc:"account avatar" gorm:"type:varchar(512);comment:Users account avatar" */
  avatar: string;
  /** @gotags: gorm:"-" json:"-" */
  update_mask: string[] | undefined;
}

function createBaseAddress(): Address {
  return { formatted: "", street_address: "", locality: "", region: "", postal_code: "", country: "" };
}

export const Address: MessageFns<Address> = {
  encode(message: Address, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.formatted !== "") {
      writer.uint32(10).string(message.formatted);
    }
    if (message.street_address !== "") {
      writer.uint32(18).string(message.street_address);
    }
    if (message.locality !== "") {
      writer.uint32(26).string(message.locality);
    }
    if (message.region !== "") {
      writer.uint32(34).string(message.region);
    }
    if (message.postal_code !== "") {
      writer.uint32(42).string(message.postal_code);
    }
    if (message.country !== "") {
      writer.uint32(50).string(message.country);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Address {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.formatted = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.street_address = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.locality = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.region = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.postal_code = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.country = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Address {
    return {
      formatted: isSet(object.formatted) ? globalThis.String(object.formatted) : "",
      street_address: isSet(object.street_address) ? globalThis.String(object.street_address) : "",
      locality: isSet(object.locality) ? globalThis.String(object.locality) : "",
      region: isSet(object.region) ? globalThis.String(object.region) : "",
      postal_code: isSet(object.postal_code) ? globalThis.String(object.postal_code) : "",
      country: isSet(object.country) ? globalThis.String(object.country) : "",
    };
  },

  toJSON(message: Address): unknown {
    const obj: any = {};
    if (message.formatted !== "") {
      obj.formatted = message.formatted;
    }
    if (message.street_address !== "") {
      obj.street_address = message.street_address;
    }
    if (message.locality !== "") {
      obj.locality = message.locality;
    }
    if (message.region !== "") {
      obj.region = message.region;
    }
    if (message.postal_code !== "") {
      obj.postal_code = message.postal_code;
    }
    if (message.country !== "") {
      obj.country = message.country;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Address>, I>>(base?: I): Address {
    return Address.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Address>, I>>(object: I): Address {
    const message = createBaseAddress();
    message.formatted = object.formatted ?? "";
    message.street_address = object.street_address ?? "";
    message.locality = object.locality ?? "";
    message.region = object.region ?? "";
    message.postal_code = object.postal_code ?? "";
    message.country = object.country ?? "";
    return message;
  },
};

function createBaseUser(): User {
  return {
    sub: "",
    name: "",
    given_name: "",
    family_name: "",
    middle_name: "",
    nickname: "",
    preferred_username: "",
    profile: "",
    picture: "",
    website: "",
    email: "",
    email_verified: false,
    gender: "",
    birthdate: "",
    zoneinfo: "",
    locale: "",
    phone_number: "",
    phone_number_verified: false,
    address: [],
    updated_at: 0,
    id: "",
    owner: "",
    type: "",
    password: "",
    password_salt: "",
    password_type: "",
    display_name: "",
    first_name: "",
    last_name: "",
    avatar: "",
    avatar_type: "",
    permanent_avatar: "",
    properties: {},
  };
}

export const User: MessageFns<User> = {
  encode(message: User, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sub !== "") {
      writer.uint32(10).string(message.sub);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.given_name !== "") {
      writer.uint32(26).string(message.given_name);
    }
    if (message.family_name !== "") {
      writer.uint32(34).string(message.family_name);
    }
    if (message.middle_name !== "") {
      writer.uint32(42).string(message.middle_name);
    }
    if (message.nickname !== "") {
      writer.uint32(50).string(message.nickname);
    }
    if (message.preferred_username !== "") {
      writer.uint32(58).string(message.preferred_username);
    }
    if (message.profile !== "") {
      writer.uint32(66).string(message.profile);
    }
    if (message.picture !== "") {
      writer.uint32(74).string(message.picture);
    }
    if (message.website !== "") {
      writer.uint32(82).string(message.website);
    }
    if (message.email !== "") {
      writer.uint32(90).string(message.email);
    }
    if (message.email_verified !== false) {
      writer.uint32(96).bool(message.email_verified);
    }
    if (message.gender !== "") {
      writer.uint32(106).string(message.gender);
    }
    if (message.birthdate !== "") {
      writer.uint32(114).string(message.birthdate);
    }
    if (message.zoneinfo !== "") {
      writer.uint32(122).string(message.zoneinfo);
    }
    if (message.locale !== "") {
      writer.uint32(130).string(message.locale);
    }
    if (message.phone_number !== "") {
      writer.uint32(138).string(message.phone_number);
    }
    if (message.phone_number_verified !== false) {
      writer.uint32(144).bool(message.phone_number_verified);
    }
    for (const v of message.address) {
      Address.encode(v!, writer.uint32(154).fork()).join();
    }
    if (message.updated_at !== 0) {
      writer.uint32(160).int64(message.updated_at);
    }
    if (message.id !== "") {
      writer.uint32(170).string(message.id);
    }
    if (message.owner !== "") {
      writer.uint32(178).string(message.owner);
    }
    if (message.type !== "") {
      writer.uint32(186).string(message.type);
    }
    if (message.password !== "") {
      writer.uint32(194).string(message.password);
    }
    if (message.password_salt !== "") {
      writer.uint32(202).string(message.password_salt);
    }
    if (message.password_type !== "") {
      writer.uint32(210).string(message.password_type);
    }
    if (message.display_name !== "") {
      writer.uint32(218).string(message.display_name);
    }
    if (message.first_name !== "") {
      writer.uint32(226).string(message.first_name);
    }
    if (message.last_name !== "") {
      writer.uint32(234).string(message.last_name);
    }
    if (message.avatar !== "") {
      writer.uint32(242).string(message.avatar);
    }
    if (message.avatar_type !== "") {
      writer.uint32(250).string(message.avatar_type);
    }
    if (message.permanent_avatar !== "") {
      writer.uint32(258).string(message.permanent_avatar);
    }
    globalThis.Object.entries(message.properties).forEach(([key, value]: [string, Any]) => {
      User_PropertiesEntry.encode({ key: key as any, value }, writer.uint32(266).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): User {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sub = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.given_name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.family_name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.middle_name = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.nickname = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.preferred_username = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.profile = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.picture = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.website = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.email_verified = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.gender = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.birthdate = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.zoneinfo = reader.string();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.locale = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.phone_number = reader.string();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.phone_number_verified = reader.bool();
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.address.push(Address.decode(reader, reader.uint32()));
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.updated_at = longToNumber(reader.int64());
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
        case 23: {
          if (tag !== 186) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 24: {
          if (tag !== 194) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 25: {
          if (tag !== 202) {
            break;
          }

          message.password_salt = reader.string();
          continue;
        }
        case 26: {
          if (tag !== 210) {
            break;
          }

          message.password_type = reader.string();
          continue;
        }
        case 27: {
          if (tag !== 218) {
            break;
          }

          message.display_name = reader.string();
          continue;
        }
        case 28: {
          if (tag !== 226) {
            break;
          }

          message.first_name = reader.string();
          continue;
        }
        case 29: {
          if (tag !== 234) {
            break;
          }

          message.last_name = reader.string();
          continue;
        }
        case 30: {
          if (tag !== 242) {
            break;
          }

          message.avatar = reader.string();
          continue;
        }
        case 31: {
          if (tag !== 250) {
            break;
          }

          message.avatar_type = reader.string();
          continue;
        }
        case 32: {
          if (tag !== 258) {
            break;
          }

          message.permanent_avatar = reader.string();
          continue;
        }
        case 33: {
          if (tag !== 266) {
            break;
          }

          const entry33 = User_PropertiesEntry.decode(reader, reader.uint32());
          if (entry33.value !== undefined) {
            message.properties[entry33.key] = entry33.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): User {
    return {
      sub: isSet(object.sub) ? globalThis.String(object.sub) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      given_name: isSet(object.given_name) ? globalThis.String(object.given_name) : "",
      family_name: isSet(object.family_name) ? globalThis.String(object.family_name) : "",
      middle_name: isSet(object.middle_name) ? globalThis.String(object.middle_name) : "",
      nickname: isSet(object.nickname) ? globalThis.String(object.nickname) : "",
      preferred_username: isSet(object.preferred_username) ? globalThis.String(object.preferred_username) : "",
      profile: isSet(object.profile) ? globalThis.String(object.profile) : "",
      picture: isSet(object.picture) ? globalThis.String(object.picture) : "",
      website: isSet(object.website) ? globalThis.String(object.website) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      email_verified: isSet(object.email_verified) ? globalThis.Boolean(object.email_verified) : false,
      gender: isSet(object.gender) ? globalThis.String(object.gender) : "",
      birthdate: isSet(object.birthdate) ? globalThis.String(object.birthdate) : "",
      zoneinfo: isSet(object.zoneinfo) ? globalThis.String(object.zoneinfo) : "",
      locale: isSet(object.locale) ? globalThis.String(object.locale) : "",
      phone_number: isSet(object.phone_number) ? globalThis.String(object.phone_number) : "",
      phone_number_verified: isSet(object.phone_number_verified)
        ? globalThis.Boolean(object.phone_number_verified)
        : false,
      address: globalThis.Array.isArray(object?.address) ? object.address.map((e: any) => Address.fromJSON(e)) : [],
      updated_at: isSet(object.updated_at) ? globalThis.Number(object.updated_at) : 0,
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      password_salt: isSet(object.password_salt) ? globalThis.String(object.password_salt) : "",
      password_type: isSet(object.password_type) ? globalThis.String(object.password_type) : "",
      display_name: isSet(object.display_name) ? globalThis.String(object.display_name) : "",
      first_name: isSet(object.first_name) ? globalThis.String(object.first_name) : "",
      last_name: isSet(object.last_name) ? globalThis.String(object.last_name) : "",
      avatar: isSet(object.avatar) ? globalThis.String(object.avatar) : "",
      avatar_type: isSet(object.avatar_type) ? globalThis.String(object.avatar_type) : "",
      permanent_avatar: isSet(object.permanent_avatar) ? globalThis.String(object.permanent_avatar) : "",
      properties: isObject(object.properties)
        ? (globalThis.Object.entries(object.properties) as [string, any][]).reduce(
          (acc: { [key: string]: Any }, [key, value]: [string, any]) => {
            acc[key] = Any.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: User): unknown {
    const obj: any = {};
    if (message.sub !== "") {
      obj.sub = message.sub;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.given_name !== "") {
      obj.given_name = message.given_name;
    }
    if (message.family_name !== "") {
      obj.family_name = message.family_name;
    }
    if (message.middle_name !== "") {
      obj.middle_name = message.middle_name;
    }
    if (message.nickname !== "") {
      obj.nickname = message.nickname;
    }
    if (message.preferred_username !== "") {
      obj.preferred_username = message.preferred_username;
    }
    if (message.profile !== "") {
      obj.profile = message.profile;
    }
    if (message.picture !== "") {
      obj.picture = message.picture;
    }
    if (message.website !== "") {
      obj.website = message.website;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.email_verified !== false) {
      obj.email_verified = message.email_verified;
    }
    if (message.gender !== "") {
      obj.gender = message.gender;
    }
    if (message.birthdate !== "") {
      obj.birthdate = message.birthdate;
    }
    if (message.zoneinfo !== "") {
      obj.zoneinfo = message.zoneinfo;
    }
    if (message.locale !== "") {
      obj.locale = message.locale;
    }
    if (message.phone_number !== "") {
      obj.phone_number = message.phone_number;
    }
    if (message.phone_number_verified !== false) {
      obj.phone_number_verified = message.phone_number_verified;
    }
    if (message.address?.length) {
      obj.address = message.address.map((e) => Address.toJSON(e));
    }
    if (message.updated_at !== 0) {
      obj.updated_at = Math.round(message.updated_at);
    }
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.password_salt !== "") {
      obj.password_salt = message.password_salt;
    }
    if (message.password_type !== "") {
      obj.password_type = message.password_type;
    }
    if (message.display_name !== "") {
      obj.display_name = message.display_name;
    }
    if (message.first_name !== "") {
      obj.first_name = message.first_name;
    }
    if (message.last_name !== "") {
      obj.last_name = message.last_name;
    }
    if (message.avatar !== "") {
      obj.avatar = message.avatar;
    }
    if (message.avatar_type !== "") {
      obj.avatar_type = message.avatar_type;
    }
    if (message.permanent_avatar !== "") {
      obj.permanent_avatar = message.permanent_avatar;
    }
    if (message.properties) {
      const entries = globalThis.Object.entries(message.properties) as [string, Any][];
      if (entries.length > 0) {
        obj.properties = {};
        entries.forEach(([k, v]) => {
          obj.properties[k] = Any.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<User>, I>>(base?: I): User {
    return User.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<User>, I>>(object: I): User {
    const message = createBaseUser();
    message.sub = object.sub ?? "";
    message.name = object.name ?? "";
    message.given_name = object.given_name ?? "";
    message.family_name = object.family_name ?? "";
    message.middle_name = object.middle_name ?? "";
    message.nickname = object.nickname ?? "";
    message.preferred_username = object.preferred_username ?? "";
    message.profile = object.profile ?? "";
    message.picture = object.picture ?? "";
    message.website = object.website ?? "";
    message.email = object.email ?? "";
    message.email_verified = object.email_verified ?? false;
    message.gender = object.gender ?? "";
    message.birthdate = object.birthdate ?? "";
    message.zoneinfo = object.zoneinfo ?? "";
    message.locale = object.locale ?? "";
    message.phone_number = object.phone_number ?? "";
    message.phone_number_verified = object.phone_number_verified ?? false;
    message.address = object.address?.map((e) => Address.fromPartial(e)) || [];
    message.updated_at = object.updated_at ?? 0;
    message.id = object.id ?? "";
    message.owner = object.owner ?? "";
    message.type = object.type ?? "";
    message.password = object.password ?? "";
    message.password_salt = object.password_salt ?? "";
    message.password_type = object.password_type ?? "";
    message.display_name = object.display_name ?? "";
    message.first_name = object.first_name ?? "";
    message.last_name = object.last_name ?? "";
    message.avatar = object.avatar ?? "";
    message.avatar_type = object.avatar_type ?? "";
    message.permanent_avatar = object.permanent_avatar ?? "";
    message.properties = (globalThis.Object.entries(object.properties ?? {}) as [string, Any][]).reduce(
      (acc: { [key: string]: Any }, [key, value]: [string, Any]) => {
        if (value !== undefined) {
          acc[key] = Any.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseUser_PropertiesEntry(): User_PropertiesEntry {
  return { key: "", value: undefined };
}

export const User_PropertiesEntry: MessageFns<User_PropertiesEntry> = {
  encode(message: User_PropertiesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      Any.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): User_PropertiesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUser_PropertiesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = Any.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): User_PropertiesEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? Any.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: User_PropertiesEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = Any.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<User_PropertiesEntry>, I>>(base?: I): User_PropertiesEntry {
    return User_PropertiesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<User_PropertiesEntry>, I>>(object: I): User_PropertiesEntry {
    const message = createBaseUser_PropertiesEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null) ? Any.fromPartial(object.value) : undefined;
    return message;
  },
};

function createBaseBasicAuth(): BasicAuth {
  return {
    uid: "",
    name: "",
    role: 0,
    audience: "",
    issuer: "",
    not_before: 0,
    expiration: 0,
    issued_at: 0,
    is_keep_login: false,
    token: "",
  };
}

export const BasicAuth: MessageFns<BasicAuth> = {
  encode(message: BasicAuth, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uid !== "") {
      writer.uint32(10).string(message.uid);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.role !== 0) {
      writer.uint32(24).int32(message.role);
    }
    if (message.audience !== "") {
      writer.uint32(34).string(message.audience);
    }
    if (message.issuer !== "") {
      writer.uint32(42).string(message.issuer);
    }
    if (message.not_before !== 0) {
      writer.uint32(48).int64(message.not_before);
    }
    if (message.expiration !== 0) {
      writer.uint32(56).int64(message.expiration);
    }
    if (message.issued_at !== 0) {
      writer.uint32(64).int64(message.issued_at);
    }
    if (message.is_keep_login !== false) {
      writer.uint32(72).bool(message.is_keep_login);
    }
    if (message.token !== "") {
      writer.uint32(82).string(message.token);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BasicAuth {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBasicAuth();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.audience = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.issuer = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.not_before = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.expiration = longToNumber(reader.int64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.issued_at = longToNumber(reader.int64());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.is_keep_login = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.token = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BasicAuth {
    return {
      uid: isSet(object.uid) ? globalThis.String(object.uid) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      role: isSet(object.role) ? roleFromJSON(object.role) : 0,
      audience: isSet(object.audience) ? globalThis.String(object.audience) : "",
      issuer: isSet(object.issuer) ? globalThis.String(object.issuer) : "",
      not_before: isSet(object.nbf)
        ? globalThis.Number(object.nbf)
        : isSet(object.not_before)
        ? globalThis.Number(object.not_before)
        : 0,
      expiration: isSet(object.exp)
        ? globalThis.Number(object.exp)
        : isSet(object.expiration)
        ? globalThis.Number(object.expiration)
        : 0,
      issued_at: isSet(object.iat)
        ? globalThis.Number(object.iat)
        : isSet(object.issued_at)
        ? globalThis.Number(object.issued_at)
        : 0,
      is_keep_login: isSet(object.is_keep_login) ? globalThis.Boolean(object.is_keep_login) : false,
      token: isSet(object.token) ? globalThis.String(object.token) : "",
    };
  },

  toJSON(message: BasicAuth): unknown {
    const obj: any = {};
    if (message.uid !== "") {
      obj.uid = message.uid;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.role !== 0) {
      obj.role = roleToJSON(message.role);
    }
    if (message.audience !== "") {
      obj.audience = message.audience;
    }
    if (message.issuer !== "") {
      obj.issuer = message.issuer;
    }
    if (message.not_before !== 0) {
      obj.nbf = Math.round(message.not_before);
    }
    if (message.expiration !== 0) {
      obj.exp = Math.round(message.expiration);
    }
    if (message.issued_at !== 0) {
      obj.iat = Math.round(message.issued_at);
    }
    if (message.is_keep_login !== false) {
      obj.is_keep_login = message.is_keep_login;
    }
    if (message.token !== "") {
      obj.token = message.token;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BasicAuth>, I>>(base?: I): BasicAuth {
    return BasicAuth.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BasicAuth>, I>>(object: I): BasicAuth {
    const message = createBaseBasicAuth();
    message.uid = object.uid ?? "";
    message.name = object.name ?? "";
    message.role = object.role ?? 0;
    message.audience = object.audience ?? "";
    message.issuer = object.issuer ?? "";
    message.not_before = object.not_before ?? 0;
    message.expiration = object.expiration ?? 0;
    message.issued_at = object.issued_at ?? 0;
    message.is_keep_login = object.is_keep_login ?? false;
    message.token = object.token ?? "";
    return message;
  },
};

function createBasePostUserRequest(): PostUserRequest {
  return {
    name: "",
    password: "",
    email: "",
    phone: "",
    role: 0,
    status: 0,
    dept: "",
    owner: "",
    avatar: "",
    tenant_id: "",
    update_mask: undefined,
  };
}

export const PostUserRequest: MessageFns<PostUserRequest> = {
  encode(message: PostUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    if (message.email !== "") {
      writer.uint32(26).string(message.email);
    }
    if (message.phone !== "") {
      writer.uint32(34).string(message.phone);
    }
    if (message.role !== 0) {
      writer.uint32(40).int32(message.role);
    }
    if (message.status !== 0) {
      writer.uint32(48).int32(message.status);
    }
    if (message.dept !== "") {
      writer.uint32(58).string(message.dept);
    }
    if (message.owner !== "") {
      writer.uint32(66).string(message.owner);
    }
    if (message.avatar !== "") {
      writer.uint32(74).string(message.avatar);
    }
    if (message.tenant_id !== "") {
      writer.uint32(82).string(message.tenant_id);
    }
    if (message.update_mask !== undefined) {
      FieldMask.encode(FieldMask.wrap(message.update_mask), writer.uint32(146).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PostUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePostUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.phone = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.dept = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.avatar = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.tenant_id = reader.string();
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.update_mask = FieldMask.unwrap(FieldMask.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PostUserRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      phone: isSet(object.phone) ? globalThis.String(object.phone) : "",
      role: isSet(object.role) ? roleFromJSON(object.role) : 0,
      status: isSet(object.status) ? uSER_STATUSFromJSON(object.status) : 0,
      dept: isSet(object.dept) ? globalThis.String(object.dept) : "",
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
      avatar: isSet(object.avatar) ? globalThis.String(object.avatar) : "",
      tenant_id: isSet(object.tenant_id) ? globalThis.String(object.tenant_id) : "",
      update_mask: isSet(object.updateMask)
        ? FieldMask.unwrap(FieldMask.fromJSON(object.updateMask))
        : isSet(object.update_mask)
        ? FieldMask.unwrap(FieldMask.fromJSON(object.update_mask))
        : undefined,
    };
  },

  toJSON(message: PostUserRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.phone !== "") {
      obj.phone = message.phone;
    }
    if (message.role !== 0) {
      obj.role = roleToJSON(message.role);
    }
    if (message.status !== 0) {
      obj.status = uSER_STATUSToJSON(message.status);
    }
    if (message.dept !== "") {
      obj.dept = message.dept;
    }
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    if (message.avatar !== "") {
      obj.avatar = message.avatar;
    }
    if (message.tenant_id !== "") {
      obj.tenant_id = message.tenant_id;
    }
    if (message.update_mask !== undefined) {
      obj.updateMask = FieldMask.toJSON(FieldMask.wrap(message.update_mask));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PostUserRequest>, I>>(base?: I): PostUserRequest {
    return PostUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PostUserRequest>, I>>(object: I): PostUserRequest {
    const message = createBasePostUserRequest();
    message.name = object.name ?? "";
    message.password = object.password ?? "";
    message.email = object.email ?? "";
    message.phone = object.phone ?? "";
    message.role = object.role ?? 0;
    message.status = object.status ?? 0;
    message.dept = object.dept ?? "";
    message.owner = object.owner ?? "";
    message.avatar = object.avatar ?? "";
    message.tenant_id = object.tenant_id ?? "";
    message.update_mask = object.update_mask ?? undefined;
    return message;
  },
};

function createBaseGetUserRequest(): GetUserRequest {
  return { uid: "" };
}

export const GetUserRequest: MessageFns<GetUserRequest> = {
  encode(message: GetUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uid !== "") {
      writer.uint32(10).string(message.uid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUserRequest {
    return { uid: isSet(object.uid) ? globalThis.String(object.uid) : "" };
  },

  toJSON(message: GetUserRequest): unknown {
    const obj: any = {};
    if (message.uid !== "") {
      obj.uid = message.uid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUserRequest>, I>>(base?: I): GetUserRequest {
    return GetUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUserRequest>, I>>(object: I): GetUserRequest {
    const message = createBaseGetUserRequest();
    message.uid = object.uid ?? "";
    return message;
  },
};

function createBaseDeleteUserRequest(): DeleteUserRequest {
  return { uid: "" };
}

export const DeleteUserRequest: MessageFns<DeleteUserRequest> = {
  encode(message: DeleteUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uid !== "") {
      writer.uint32(10).string(message.uid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteUserRequest {
    return { uid: isSet(object.uid) ? globalThis.String(object.uid) : "" };
  },

  toJSON(message: DeleteUserRequest): unknown {
    const obj: any = {};
    if (message.uid !== "") {
      obj.uid = message.uid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteUserRequest>, I>>(base?: I): DeleteUserRequest {
    return DeleteUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteUserRequest>, I>>(object: I): DeleteUserRequest {
    const message = createBaseDeleteUserRequest();
    message.uid = object.uid ?? "";
    return message;
  },
};

function createBaseDeleteUserResponse(): DeleteUserResponse {
  return { uid: "" };
}

export const DeleteUserResponse: MessageFns<DeleteUserResponse> = {
  encode(message: DeleteUserResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uid !== "") {
      writer.uint32(10).string(message.uid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteUserResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteUserResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uid = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteUserResponse {
    return { uid: isSet(object.uid) ? globalThis.String(object.uid) : "" };
  },

  toJSON(message: DeleteUserResponse): unknown {
    const obj: any = {};
    if (message.uid !== "") {
      obj.uid = message.uid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteUserResponse>, I>>(base?: I): DeleteUserResponse {
    return DeleteUserResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteUserResponse>, I>>(object: I): DeleteUserResponse {
    const message = createBaseDeleteUserResponse();
    message.uid = object.uid ?? "";
    return message;
  },
};

function createBasePatchUserRequest(): PatchUserRequest {
  return {
    uid: "",
    name: "",
    password: "",
    email: "",
    phone: "",
    role: 0,
    status: 0,
    dept: "",
    owner: "",
    avatar: "",
    update_mask: undefined,
  };
}

export const PatchUserRequest: MessageFns<PatchUserRequest> = {
  encode(message: PatchUserRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uid !== "") {
      writer.uint32(10).string(message.uid);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.password !== "") {
      writer.uint32(26).string(message.password);
    }
    if (message.email !== "") {
      writer.uint32(34).string(message.email);
    }
    if (message.phone !== "") {
      writer.uint32(42).string(message.phone);
    }
    if (message.role !== 0) {
      writer.uint32(48).int32(message.role);
    }
    if (message.status !== 0) {
      writer.uint32(56).int32(message.status);
    }
    if (message.dept !== "") {
      writer.uint32(66).string(message.dept);
    }
    if (message.owner !== "") {
      writer.uint32(74).string(message.owner);
    }
    if (message.avatar !== "") {
      writer.uint32(82).string(message.avatar);
    }
    if (message.update_mask !== undefined) {
      FieldMask.encode(FieldMask.wrap(message.update_mask), writer.uint32(146).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PatchUserRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePatchUserRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.phone = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.dept = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.owner = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.avatar = reader.string();
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.update_mask = FieldMask.unwrap(FieldMask.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PatchUserRequest {
    return {
      uid: isSet(object.uid) ? globalThis.String(object.uid) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      phone: isSet(object.phone) ? globalThis.String(object.phone) : "",
      role: isSet(object.role) ? roleFromJSON(object.role) : 0,
      status: isSet(object.status) ? uSER_STATUSFromJSON(object.status) : 0,
      dept: isSet(object.dept) ? globalThis.String(object.dept) : "",
      owner: isSet(object.owner) ? globalThis.String(object.owner) : "",
      avatar: isSet(object.avatar) ? globalThis.String(object.avatar) : "",
      update_mask: isSet(object.updateMask)
        ? FieldMask.unwrap(FieldMask.fromJSON(object.updateMask))
        : isSet(object.update_mask)
        ? FieldMask.unwrap(FieldMask.fromJSON(object.update_mask))
        : undefined,
    };
  },

  toJSON(message: PatchUserRequest): unknown {
    const obj: any = {};
    if (message.uid !== "") {
      obj.uid = message.uid;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.phone !== "") {
      obj.phone = message.phone;
    }
    if (message.role !== 0) {
      obj.role = roleToJSON(message.role);
    }
    if (message.status !== 0) {
      obj.status = uSER_STATUSToJSON(message.status);
    }
    if (message.dept !== "") {
      obj.dept = message.dept;
    }
    if (message.owner !== "") {
      obj.owner = message.owner;
    }
    if (message.avatar !== "") {
      obj.avatar = message.avatar;
    }
    if (message.update_mask !== undefined) {
      obj.updateMask = FieldMask.toJSON(FieldMask.wrap(message.update_mask));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PatchUserRequest>, I>>(base?: I): PatchUserRequest {
    return PatchUserRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PatchUserRequest>, I>>(object: I): PatchUserRequest {
    const message = createBasePatchUserRequest();
    message.uid = object.uid ?? "";
    message.name = object.name ?? "";
    message.password = object.password ?? "";
    message.email = object.email ?? "";
    message.phone = object.phone ?? "";
    message.role = object.role ?? 0;
    message.status = object.status ?? 0;
    message.dept = object.dept ?? "";
    message.owner = object.owner ?? "";
    message.avatar = object.avatar ?? "";
    message.update_mask = object.update_mask ?? undefined;
    return message;
  },
};

export interface UserService {
  /**
   * rpc Register(PostUserRequest) returns (User){
   *     option (google.api.http)={
   *         post:"/api/v1/users"
   *         body:"*"
   *     };
   * };
   * rpc Update(PatchUserRequest) returns (User){
   *     option (google.api.http)={
   *         put:"/api/v1/users/{uid}"
   *         body:"*"
   *     };
   */
  Get(request: Empty): Promise<User>;
}

export const UserServiceServiceName = "stew.api.v1.UserService";
export class UserServiceClientImpl implements UserService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || UserServiceServiceName;
    this.rpc = rpc;
    this.Get = this.Get.bind(this);
  }
  Get(request: Empty): Promise<User> {
    const data = Empty.encode(request).finish();
    const promise = this.rpc.request(this.service, "Get", data);
    return promise.then((data) => User.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
